# Global variables with default values used in packages.
logger.g_in_plugin_error = 'false'
logger.g_log_id = ''
logger.g_plug_logger_log_error = ''
logger.g_proc_start_times = ''
logger.g_running_timers = '0'
logger.gc_cflf = 'chr(13)||chr(10)'
logger.gc_ctx_attr_include_call_stack = 'include_call_stack'
logger.gc_ctx_attr_level = 'level'
logger.gc_ctx_plugin_fn_error = 'plugin_fn_error'
logger.gc_ctx_plugin_fn_info = 'plugin_fn_information'
logger.gc_ctx_plugin_fn_log = 'plugin_fn_log'
logger.gc_ctx_plugin_fn_perm = 'plugin_fn_permanent'
logger.gc_ctx_plugin_fn_warn = 'plugin_fn_warning'
logger.gc_date_format = 'DD-MON-YYYY HH24:MI:SS'
logger.gc_line_feed = 'chr(10)'
logger.gc_pref_client_id_expire_hours = 'PREF_BY_CLIENT_ID_EXPIRE_HOURS'
logger.gc_pref_include_call_stack = 'INCLUDE_CALL_STACK'
logger.gc_pref_install_schema = 'INSTALL_SCHEMA'
logger.gc_pref_level = 'LEVEL'
logger.gc_pref_logger_debug = 'LOGGER_DEBUG'
logger.gc_pref_logger_version = 'LOGGER_VERSION'
logger.gc_pref_plugin_fn_error = 'PLUGIN_FN_ERROR'
logger.gc_pref_protect_admin_procs = 'PROTECT_ADMIN_PROCS'
logger.gc_pref_purge_after_days = 'PURGE_AFTER_DAYS'
logger.gc_pref_purge_min_level = 'PURGE_MIN_LEVEL'
logger.gc_timestamp_format = 'gc_date_format || \':FF\'
logger.gc_timestamp_tz_format = 'gc_timestamp_format || \' TZR\'
