-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



-- Oracle package 'logger' declaration, please edit to match PostgreSQL syntax.
CREATE TYPE logger.ts_array AS (ts_array timestamp[]);



-- Note: The license is defined in the package specification of the logger package
  --
  -- Conditional Compilation variables:
  -- $$NO_OP
  --  When true, completely disables all logger DML.Also used to generate the logger_no_op.sql file
  --
  -- $$RAC_LT_11_2:
  --  Set in logger_configure.
  --  Handles the fact that RAC doesn't support global app contexts until 11.2
  --
  -- $$FLASHBACK_ENABLED
  --  Set in logger_configure.
  --  Determine whether or not we can grab the scn from dbms_flashback.
  --  Primarily used in the trigger on logger_logs.
  --
  -- $$APEX
  --  Set in logger_configure.
  --  True if we can query a local synonym to wwv_flow_data to snapshot the APEX session state.
  --
  -- $$LOGGER_DEBUG
  --  Only to be used during development of logger
  --  Primarily used for dbms_output.put_line calls
  --  Part of #64
  --
  -- $$LOGGER_PLUGIN_<TYPE> : For each type of plugin
  --  Introduced with #46
  --  $$LOGGER_PLUGIN_ERROR
  --
  -- TYPES
  


  -- VARIABLES
  

  -- #46
  






  -- CONSTANTS
  

  -- #46 Plugin context names
  

  -- #113 Preference names
  




  -- *** PRIVATE ***
  /**
   *
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Martin D'Souza
   * @created
   * @param p_str
   * @return True if p_str is a number
   */
CREATE OR REPLACE FUNCTION logger_is_number (p_str text) RETURNS boolean AS $body$
DECLARE

    l_num bigint;

BEGIN
    l_num := (p_str)::numeric;
    return true;
  exception
    when others then
      return false;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_is_number (p_str text) FROM PUBLIC;


  /**
   * Validates assertion. Will raise an application error if assertion is false
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Martin D'Souza
   * @created 29-Mar-2013
   * @param p_condition Boolean condition to validate
   * @param p_message Message to include in application error if p_condition fails
   */
CREATE OR REPLACE PROCEDURE logger_assert ( p_condition boolean, p_message text) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      if not p_condition or coalesce(p_condition::text, '') = '' then
        RAISE EXCEPTION '%', p_message USING ERRCODE = '45000';
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_assert ( p_condition boolean, p_message text) FROM PUBLIC;


  /**
   * Returns the display/print friendly parameter information
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Martin D'Souza
   * @created 20-Jan-2013
   * @param p_parms Array of parameters (can be null)
   * @return Clob of param information
   */
CREATE OR REPLACE FUNCTION logger_get_param_clob (p_params logger.tab_param) RETURNS text AS $body$
DECLARE

    l_return text;
    l_no_vars constant varchar(255) := 'No params defined';
    l_index integer;

BEGIN

    $if $$no_op $then
      return null;
    $else
      -- Generate line feed delimited list
      if p_params.count > 0 then
        -- Using while true ... option allows for unordered param list
        l_index := p_params.first;
        while true loop
          l_return := l_return || p_params[l_index].name || ': ' || p_params[l_index].val;

          l_index := p_params.next(l_index);

          if coalesce(l_index::text, '') = '' then
            exit;
          else
            l_return := l_return || current_setting('logger.gc_line_feed')::varchar(1);
          end if;
        end loop;

      else
        -- No Parameters
        l_return := l_no_vars;
      end if;

      return l_return;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_get_param_clob (p_params logger.tab_param) FROM PUBLIC;

--
-- dblink wrapper to call function logger_save_global_context as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_save_global_context ( p_attribute text, p_value text, p_client_id text default null) AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_save_global_context_atx ( ' || quote_nullable(p_attribute) || ',' || quote_nullable(p_value) || ',' || quote_nullable(p_client_id) || ' )';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;




  /**
   * Sets the global context
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_attribute Attribute for context to set
   * @param p_value Value
   * @param p_client_id Optional client_id. If specified will only set the attribute/value for specific client_id (not global)
   */
CREATE OR REPLACE PROCEDURE logger_save_global_context_atx ( p_attribute text, p_value text, p_client_id text default null) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      dbms_session.set_context(
        namespace => g_context_name,
        attribute => p_attribute,
        value => p_value,
        client_id => p_client_id);
    $END; -- MD: moved commit to outside of the NO_OP check since commit or rollback must occur in this procedure
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_save_global_context ( p_attribute text, p_value text, p_client_id text default null) FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_save_global_context_atx ( p_attribute text, p_value text, p_client_id text default null) FROM PUBLIC;



  /**
   * Will return the extra column appended with the display friendly parameters
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Martin D'Souza
   * @created 1-May-2013
   * @param p_extra Current "Extra" field
   * @param p_params Parameters. If null, then no changes to the Extra column
   */
CREATE OR REPLACE FUNCTION logger_set_extra_with_params ( p_extra logger_logs.extra%type, p_params tab_param ) RETURNS LOGGER_LOGS.EXTRA%TYPE AS $body$
DECLARE

    l_extra logger_logs.extra%type;

BEGIN
    $if $$no_op $then
      return null;
    $else
      if p_params.count = 0 then
        return p_extra;
      else
        l_extra := p_extra || current_setting('logger.gc_line_feed')::varchar(1) || current_setting('logger.gc_line_feed')::varchar(1) || '*** Parameters ***' || current_setting('logger.gc_line_feed')::varchar(1) || current_setting('logger.gc_line_feed')::varchar(1) || logger_get_param_clob(p_params => p_params);
      end if;

      return l_extra;
    $end

  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_set_extra_with_params ( p_extra logger_logs.extra%type, p_params tab_param ) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_ctx (p_name text) AS $body$
DECLARE

      r_pad bigint := 30;
      l_value varchar(100);

      invalid_userenv_parm exception;


    
BEGIN
      l_value := sys_context('USERENV',p_name);

      if p_show_null or (l_value IS NOT NULL AND l_value::text <> '') then
        if p_vertical then
          l_ctx := l_ctx || rpad(p_name,r_pad,' ')||': '|| l_value || current_setting('logger.gc_cflf')::varchar(2);
        else
          l_ctx := l_ctx || p_name||': '|| l_value ||', ';
        end if;
      end if;
    exception
      when invalid_userenv_parm then
        null;
    END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_ctx (p_name text) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  - #111 Use get_pref to remove duplicate code
   *
   * @author Tyler Muth
   * @created ???
   * @param
   * @return If client level specified will return it, otherwise global level.
   */
CREATE OR REPLACE FUNCTION logger_get_level_number () RETURNS bigint AS $body$
DECLARE

    l_level bigint;
    l_level_char varchar(50);

    $if $$logger_debug $then
      l_scope varchar(30) := 'get_level_number';
    $END;
BEGIN
    $if $$no_op $then
      return g_off;
    $else
      $if $$logger_debug $then
        RAISE NOTICE '%: selecting logger_level', l_scope;
      $end

      l_level := logger_convert_level_char_to_num(logger_get_pref(current_setting('logger.gc_pref_level')::logger_prefs.pref_name%type));

      return l_level;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_get_level_number () FROM PUBLIC;


  /**
   * Determines if callstack should be while logging
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @return
   */
CREATE OR REPLACE FUNCTION logger_include_call_stack () RETURNS boolean AS $body$
DECLARE
 null or not $$no_op) $then
        result_cache relies_on(logger_prefs, logger_prefs_by_client_id)
    $end
  is
    l_call_stack_pref logger_prefs.pref_value%type;

BEGIN
    $if $$no_op $then
      return false;
    $else
      $if $$rac_lt_11_2 $then
        l_call_stack_pref := logger_get_pref(current_setting('logger.gc_pref_include_call_stack')::logger_prefs.pref_name%type);
      $else
        l_call_stack_pref := sys_context(g_context_name,current_setting('logger.gc_ctx_attr_include_call_stack')::varchar(18));

        if coalesce(l_call_stack_pref::text, '') = '' then
          l_call_stack_pref := logger_get_pref(current_setting('logger.gc_pref_include_call_stack')::logger_prefs.pref_name%type);
          CALL logger_save_global_context(
            p_attribute => current_setting('logger.gc_ctx_attr_include_call_stack')::varchar(18),
            p_value => l_call_stack_pref,
            p_client_id => sys_context('userenv','client_identifier'));
        end if;
      $end

      if l_call_stack_pref = 'TRUE' then
        return true;
      else
        return false;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_include_call_stack () FROM PUBLIC;


  /**
   * Returns date diff in "... sectons/minutes/days/etc ago" format
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_date_start
   * @param p_date_stop
   * @return Text version of date diff
   */
CREATE OR REPLACE FUNCTION logger_date_text_format_base ( p_date_start timestamp(0), p_date_stop timestamp(0)) RETURNS varchar AS $body$
DECLARE

    x varchar(20);

BEGIN
    $if $$no_op $then
      return null;
    $else
      x :=
        case
          when p_date_stop-p_date_start < 1/1440
            then round(24*60*60*(p_date_stop-p_date_start)) || ' seconds'
          when p_date_stop-p_date_start < 1/24
            then round(24*60*(p_date_stop-p_date_start)) || ' minutes'
          when p_date_stop-p_date_start < 1
            then round(24*(p_date_stop-p_date_start)) || ' hours'
          when p_date_stop-p_date_start < 14
            then date_trunc('day', p_date_stop-p_date_start) || ' days'
          when p_date_stop-p_date_start < 60
            then trunc((p_date_stop-p_date_start)/7) || ' weeks'
          when p_date_stop-p_date_start < 365
            then round(months_between(p_date_stop,p_date_start)) || ' months'
          else round((months_between(p_date_stop,p_date_start)/12)::numeric,1) || ' years'
        end;
      x:= regexp_replace(x,'(^1 [[:alnum:]]{4,10})s','\1', 'g');
      x:= x || ' ago';
      return substr(x,1,20);
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_date_text_format_base ( p_date_start timestamp(0), p_date_stop timestamp(0)) FROM PUBLIC;


  /**
   * Parses the callstack to get unit and line number
   *
   * Notes:
   *  - Private
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_callstack
   * @param o_unit
   * @param o_lineno
   */
CREATE OR REPLACE PROCEDURE logger_get_debug_info ( p_callstack text, o_unit INOUT text, o_lineno INOUT text ) AS $body$
DECLARE

    --
    l_callstack varchar(10000) := p_callstack;

BEGIN
    $if $$no_op $then
      null;
    $else
      l_callstack := substr( l_callstack, instr( l_callstack, chr(10), 1, 5 )+1 );
      l_callstack := substr( l_callstack, 1, instr( l_callstack, chr(10), 1, 1 )-1 );
      l_callstack := trim(both substr( l_callstack, position(' '  in l_callstack) ) );
      o_lineno := substr( l_callstack, 1, position(' '  in l_callstack)-1 );
      o_unit := trim(both substr( l_callstack, instr( l_callstack, ' ', -1, 1 ) ));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_get_debug_info ( p_callstack text, o_unit INOUT text, o_lineno INOUT text ) FROM PUBLIC;


  /**
   * Main procedure that will store log data into logger_logs table
   *
   *
   * Modifications
   *  - 2.1.0: If text is > 4000 characters, it will be moved to the EXTRA column
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_log_level
   * @param p_scope
   * @param p_extra
   * @param p_callstack
   * @param p_params
   *
   */
CREATE OR REPLACE PROCEDURE logger_log_internal ( p_text text, p_log_level bigint, p_scope text, p_extra text default null, p_callstack text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
DECLARE

    l_proc_name varchar(100);
    l_lineno varchar(100);
    l_text varchar(32767);
    l_callstack varchar(3000);
    l_extra logger_logs.extra%type;

BEGIN
    $if $$no_op $then
      null;
    $else
      l_text := p_text;

      -- Generate callstack text
      if (p_callstack IS NOT NULL AND p_callstack::text <> '') and logger_include_call_stack() then
        SELECT * FROM logger_get_debug_info(
          p_callstack => p_callstack, o_unit => l_proc_name, o_lineno => l_lineno) INTO STRICT l_proc_name, l_lineno;

        l_callstack  := regexp_replace(p_callstack,'^.*$','',1,4,'m', 'g');
        l_callstack  := regexp_replace(l_callstack,'^.*$','',1,1,'m', 'g');
        l_callstack  := ltrim(replace(l_callstack,chr(10)||chr(10),chr(10)),chr(10));

      end if;

      l_extra := logger_set_extra_with_params(p_extra => p_extra, p_params => p_params);

      current_setting('logger.g_log_id')::bigint := logger_ins_logger_logs(
        p_unit_name => upper(l_proc_name), p_scope => p_scope, p_logger_level =>p_log_level, p_extra => l_extra, p_text =>l_text, p_call_stack  =>l_callstack, p_line_no => l_lineno, po_id => current_setting('logger.g_log_id')::bigint);
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_internal ( p_text text, p_log_level bigint, p_scope text, p_extra text default null, p_callstack text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_start_stop_plugin ( p_in_plugin boolean  -- True/False depending on action
 ) AS $body$
BEGIN
      if p_logger_log.logger_level = logger.g_error then
        PERFORM set_config('logger.g_in_plugin_error', p_in_plugin, false);
      end if;
    END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_start_stop_plugin ( p_in_plugin boolean  ) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_f_get_set_global_context ( p_ctx text ) RETURNS varchar AS $body$
DECLARE

      l_return varchar(255);

BEGIN
      $if $$logger_debug $then
        RAISE NOTICE 'Calling f_get_set_global_conext';
      $end

      l_return := upper(logger_get_pref(p_pref_name =>
        case
          when p_logger_log.logger_level = g_error then current_setting('logger.gc_ctx_plugin_fn_error')::varchar(30)
        end
      ));

      $if $$logger_debug $then
        RAISE NOTICE 'l_return: %', l_return;
      $end

      logger_save_global_context(p_attribute => p_ctx, p_value => l_return);
      return l_return;
    END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_f_get_set_global_context ( p_ctx text ) FROM PUBLIC;


  /**
   * Converts string names to text value
   *
   * Changes
   *  - 2.1.0: Start to use global variables and correct numbers
   *
   * @author Tyler Muth
   * @created ???
   *
   * @param p_level String representation of level
   * @return level number. -1 if not found
   */
CREATE OR REPLACE FUNCTION logger_convert_level_char_to_num ( p_level text) RETURNS bigint AS $body$
DECLARE

    l_level         bigint;

BEGIN
    $if $$no_op $then
      return null;
    $else
      case p_level
        when g_off_name then l_level := g_off;
        when g_permanent_name then l_level := g_permanent;
        when g_error_name then l_level := g_error;
        when g_warning_name then l_level := g_warning;
        when g_information_name then l_level := g_information;
        when g_debug_name then l_level := g_debug;
        when g_timing_name then l_level := g_timing;
        when g_sys_context_name then l_level := g_sys_context;
        when g_apex_name then l_level := g_apex;
        else l_level := -1;
      end case;
    $end

    return l_level;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_convert_level_char_to_num ( p_level text) FROM PUBLIC;


  /**
   * Converts the logger level num to char format
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #48
   *
   * @author Martin D'Souza
   * @created 14-Jun-2014
   * @param p_level
   * @return Logger level string format
   */
CREATE OR REPLACE FUNCTION logger_convert_level_num_to_char ( p_level bigint) RETURNS varchar AS $body$
DECLARE

    l_return varchar(255);

BEGIN
    $if $$no_op $then
      null;
    $else
      l_return :=
        case p_level
          when g_off then g_off_name
          when g_permanent then g_permanent_name
          when g_error then g_error_name
          when g_warning then g_warning_name
          when g_information then g_information_name
          when g_debug then g_debug_name
          when g_timing then g_timing_name
          when g_sys_context then g_sys_context_name
          when g_apex then g_apex_name
          else null
        end;
    $end

    return l_return;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_convert_level_num_to_char ( p_level bigint) FROM PUBLIC;





  /**
   * Determines if the statement can be stored in LOGGER_LOGS
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #44: Expose publically
   *
   * @author Tyler Muth
   * @created ???
   *
   * @param p_level Level (number)
   * @return True of statement can be logged to LOGGER_LOGS
   */
CREATE OR REPLACE FUNCTION logger_ok_to_log (p_level bigint) RETURNS boolean AS $body$
DECLARE
 null or not $$no_op) $then
        result_cache relies_on(logger_prefs, logger_prefs_by_client_id)
    $end
  is
    l_level bigint;
    l_level_char varchar(50);

    $if $$logger_debug $then
      l_scope varchar(30) := 'ok_to_log';
    $END;
BEGIN
    $if $$no_op $then
      return false;
    $else

      $if $$logger_debug $then
        RAISE NOTICE '%: in function', l_scope;
      $end

      $if $$rac_lt_11_2 $then
        $if $$logger_debug $then
          RAISE NOTICE '%: calling get_level_number', l_scope;
        $end
        l_level := logger_get_level_number;
      $else
        l_level := sys_context(g_context_name,current_setting('logger.gc_ctx_attr_level')::varchar(5));

        if coalesce(l_level::text, '') = '' then
          $if $$logger_debug $then
            RAISE NOTICE '%: level was null, getting and setting in context', l_scope;
          $end

          l_level := logger_get_level_number;

          CALL logger_save_global_context(
            p_attribute => current_setting('logger.gc_ctx_attr_level')::varchar(5),
            p_value => l_level,
            p_client_id => sys_context('userenv','client_identifier'));
        end if;
      $end

      if l_level >= p_level then
        return true;
      else
        return false;
      end if;
   $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_ok_to_log (p_level bigint) FROM PUBLIC;


  /**
   * Determines if log statements will actually be stored.
   *
   * @author Martin D'Souza
   * @created 25-Jul-2013
   *
   * @param p_level Level (DEBUG etc..)
   * @return True of log statements for that level or below will be logged
   */
CREATE OR REPLACE FUNCTION logger_ok_to_log (p_level text) RETURNS boolean AS $body$
BEGIN
    $if $$no_op $then
      return false;
    $else
      return logger_ok_to_log(p_level => logger_convert_level_char_to_num(p_level => p_level));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_ok_to_log (p_level text) FROM PUBLIC;




  /**
   * ???
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_date
   * @return
   */
CREATE OR REPLACE FUNCTION logger_date_text_format (p_date timestamp(0)) RETURNS varchar AS $body$
BEGIN
    $if $$no_op $then
      return null;
    $else
      return logger_date_text_format_base(
        p_date_start => p_date   ,
        p_date_stop  => clock_timestamp());
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_date_text_format (p_date timestamp(0)) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_get_character_codes ( p_string text, p_show_common_codes boolean default true) RETURNS varchar AS $body$
DECLARE

    l_string  varchar(32767);
    l_dump    varchar(32767);
    l_return  varchar(32767);

BEGIN
    -- replace tabs with ^
    l_string := replace(p_string,chr(9),'^');
    -- replace all other control characters such as carriage return / line feeds with ~
    l_string := regexp_replace(l_string,'[[:cntrl:]]','~',1,0,'m', 'g');

    select dump(p_string) into STRICT l_dump;

    l_dump  := regexp_replace(l_dump,'(^.+?:)(.*)','\2',1,0, 'g'); -- get everything after the :
    l_dump  := ','||l_dump||','; -- leading and trailing commas
    l_dump  := replace(l_dump,',',',,'); -- double the commas. this is for the regex.
    l_dump  := regexp_replace(l_dump,'(,)([[:digit:]]{1})(,)','\1  \2\3',1,0, 'g'); -- lpad all single digit numbers out to 3
    l_dump  := regexp_replace(l_dump,'(,)([[:digit:]]{2})(,)','\1 \2\3',1,0, 'g');  -- lpad all double digit numbers out to 3
    l_dump  := ltrim(replace(l_dump,',,',','),','); -- remove the double commas
    l_dump  := lpad(' ',(5-position(',' in l_dump)),' ')||l_dump;

    -- replace every individual character with 2 spaces, itself and a comma so it lines up with the dump output
    l_string := ' '||regexp_replace(l_string,'(.){1}','  \1,',1,0, 'g');

    l_return := rtrim(l_dump,',') || chr(10) || rtrim(l_string,',');

    if p_show_common_codes then
      l_return := 'Common Codes: 13=Line Feed, 10=Carriage Return, 32=Space, 9=Tab'||chr(10) ||l_return;
    end if;

    return l_return;

  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_get_character_codes ( p_string text, p_show_common_codes boolean default true) FROM PUBLIC;

  /**
   * Store APEX items in logger_logs_apex_items
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #115: Only log not-null values
   *  - #114: Bulk insert (no more row by row)
   *  - #54: Support for p_item_type
   *
   * @author Tyler Muth
   * @created ???
   * @param p_log_id logger_logs.id to reference
   * @param p_item_type Either the g_apex_item_type_... type or just the APEX page number for a specific page. It is assumed that it has been validated by the time it hits here.
   * @param p_log_null_items If set to false, null values won't be logged
   */
CREATE OR REPLACE PROCEDURE logger_snapshot_apex_items ( p_log_id logger_logs.id%type, p_item_type text, p_log_null_items boolean) AS $body$
DECLARE

    l_app_session bigint;
    l_app_id bigint;
    l_log_null_item_yn varchar(1);
    l_item_type varchar(30) := upper(p_item_type);
    l_item_type_page_id bigint;

BEGIN
    $if $$no_op $then
      null;
    $else
      $if $$apex $then
        l_app_session := v('APP_SESSION');
        l_app_id := v('APP_ID');

        l_log_null_item_yn := 'N';
        if p_log_null_items then
          l_log_null_item_yn := 'Y';
        end if;

        if logger_is_number(l_item_type) then
          l_item_type_page_id := (l_item_type)::numeric;
        end if;

        insert into logger_logs_apex_items(log_id,app_session,item_name,item_value)
        SELECT p_log_id, l_app_session, item_name, item_value
        from (
          -- Application items
          SELECT 1 app_page_seq, 0 page_id, item_name, v(item_name) item_value
          from apex_application_items
          where 1=1
            and application_id = l_app_id
            and l_item_type in (logger.g_apex_item_type_all, logger.g_apex_item_type_app)
          
union all

          -- Application page items
          select 2 app_page_seq, page_id, item_name, v(item_name) item_value
          from apex_application_page_items
          where 1=1
            and application_id = l_app_id
            and (
              1=2
              or l_item_type in (logger.g_apex_item_type_all, logger.g_apex_item_type_page)
              or ((l_item_type_page_id IS NOT NULL AND l_item_type_page_id::text <> '') and l_item_type_page_id = page_id)
            ) 
          ) alias8
        where 1=1
          and (l_log_null_item_yn = 'Y' or (item_value IS NOT NULL AND item_value::text <> '')) 
        order by app_page_seq, page_id, item_name;

      $end  -- $if $$apex $then
      null; -- Keep this in place incase APEX is not compiled
    $end  -- $$no_op
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_snapshot_apex_items ( p_log_id logger_logs.id%type, p_item_type text, p_log_null_items boolean) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #46: Added plugin support
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_error ( p_text text default null, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
DECLARE

    l_proc_name varchar(100);
    l_lineno varchar(100);
    l_text varchar(32767);
    l_call_stack varchar(4000);
    l_extra text;

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_error) then
        SELECT * FROM logger_get_debug_info(
          p_callstack => dbms_utility.format_call_stack, o_unit => l_proc_name, o_lineno => l_lineno) INTO STRICT l_proc_name, l_lineno;

        l_call_stack := dbms_utility.format_error_stack() || current_setting('logger.gc_line_feed')::varchar(1) || dbms_utility.format_error_backtrace;

        if (p_text IS NOT NULL AND p_text::text <> '') then
          l_text := p_text || current_setting('logger.gc_line_feed')::varchar(1) || current_setting('logger.gc_line_feed')::varchar(1);
        end if;

        l_text := l_text || dbms_utility.format_error_stack();

        l_extra := logger_set_extra_with_params(p_extra => p_extra, p_params => p_params);

        current_setting('logger.g_log_id')::bigint := logger_ins_logger_logs(
          p_unit_name => upper(l_proc_name), p_scope => p_scope, p_logger_level => logger.g_error, p_extra => l_extra, p_text => l_text, p_call_stack => l_call_stack, p_line_no => l_lineno, po_id => current_setting('logger.g_log_id')::bigint);

        -- Plugin
        $if $$logger_plugin_error $then

          if not current_setting('logger.g_in_plugin_error')::boolean then
            current_setting('logger.g_plug_logger_log_error')::rec_logger_log.logger_level := logger.g_error;
            current_setting('logger.g_plug_logger_log_error')::rec_logger_log.id := current_setting('logger.g_log_id')::bigint;

            $if $$logger_debug $then
              RAISE NOTICE 'Starting call to run_plugin error';
            $end

            run_plugin(p_logger_log => current_setting('logger.g_plug_logger_log_error')::rec_logger_log);
          end if; -- not g_in_plugin_error
        $end

      end if; -- ok_to_log
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_error ( p_text text default null, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_permanent ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_permanent) then
        CALL logger_log_internal(
          p_text => p_text,
          p_log_level => logger.g_permanent,
          p_scope => p_scope,
          p_extra => p_extra,
          p_callstack => dbms_utility.format_call_stack,
          p_params => p_params
        );
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_permanent ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_warning ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_warning) then
        CALL logger_log_internal(
          p_text => p_text,
          p_log_level => logger.g_warning,
          p_scope => p_scope,
          p_extra => p_extra,
          p_callstack => dbms_utility.format_call_stack,
          p_params => p_params);
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_warning ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;


  /**
   * Wrapper for log_warning
   *
   * Notes:
   *  - #80
   *
   * Related Tickets:
   *  -
   *
   * @author Martin D'Souza
   * @created 9-9-Mar-2015
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_warn ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN
    CALL logger_log_warning(
      p_text => p_text,
      p_scope => p_scope,
      p_extra => p_extra,
      p_params => p_params
    );
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_warn ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;

  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_information ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_information) then
        CALL logger_log_internal(
          p_text => p_text,
          p_log_level => logger.g_information,
          p_scope => p_scope,
          p_extra => p_extra,
          p_callstack => dbms_utility.format_call_stack,
          p_params => p_params);
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_information ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;


  /**
   * Wrapper for short call to log_information
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #80
   *
   * @author Martin D'Souza
   * @created 9-Mar-2015
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log_info ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN
    CALL logger_log_information(
      p_text => p_text,
      p_scope => p_scope,
      p_extra => p_extra,
      p_params => p_params
    );
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_info ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_extra
   * @param p_params
   */
CREATE OR REPLACE PROCEDURE logger_log ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) AS $body$
BEGIN

    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        CALL logger_log_internal(
          p_text => p_text,
          p_log_level => logger.g_debug,
          p_scope => p_scope,
          p_extra => p_extra,
          p_callstack => dbms_utility.format_call_stack,
          p_params => p_params);
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log ( p_text text, p_scope text default null, p_extra text default null, p_params tab_param default logger.gc_empty_tab_param) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_cgi_env ( p_name text, p_val text) AS $body$
DECLARE

        r_pad bigint := 30;

BEGIN
        if p_show_null or (p_val IS NOT NULL AND p_val::text <> '') then
          l_cgienv := l_cgienv || rpad(p_name,r_pad,' ')||': '||p_val||current_setting('logger.gc_cflf')::varchar(2);
        end if;
      END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_cgi_env ( p_name text, p_val text) FROM PUBLIC;


  /**
   * Logs CGI environment variables
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_show_null
   * @param p_scope
   * @param p_level Highest level to run at (default logger.g_debug). Example. If you set to logger.g_error it will work when both in DEBUG and ERROR modes. However if set to logger.g_debug(default) will not store values when level is set to ERROR.
   */
CREATE OR REPLACE PROCEDURE logger_log_cgi_env ( p_show_null boolean default false, p_scope logger_logs.scope%type default null, p_level logger_logs.logger_level%type default null) AS $body$
DECLARE

    l_extra text;

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(coalesce(p_level, logger.g_debug)) then
        l_extra := get_cgi_env(p_show_null    => p_show_null);
        CALL logger_log_internal(
          p_text => 'CGI ENV values stored in the EXTRA column',
          p_log_level => coalesce(p_level, logger.g_sys_context),
          p_scope => p_scope,
          p_extra => l_extra);
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_cgi_env ( p_show_null boolean default false, p_scope logger_logs.scope%type default null, p_level logger_logs.logger_level%type default null) FROM PUBLIC;


  /**
   * Logs character codes for given string
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_show_common_codes
   * @param p_level Highest level to run at (default logger.g_debug). Example. If you set to logger.g_error it will work when both in DEBUG and ERROR modes. However if set to logger.g_debug(default) will not store values when level is set to ERROR.
   */
CREATE OR REPLACE PROCEDURE logger_log_character_codes ( p_text text, p_scope logger_logs.scope%type default null, p_show_common_codes boolean default true, p_level logger_logs.logger_level%type default null) AS $body$
DECLARE

    l_error varchar(4000);
    l_dump text;

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(coalesce(p_level, logger.g_debug)) then
        l_dump := logger_get_character_codes(p_text,p_show_common_codes);

        CALL logger_log_internal(
          p_text => 'GET_CHARACTER_CODES output stored in the EXTRA column',
          p_log_level => coalesce(p_level, logger.g_debug),
          p_scope => p_scope,
          p_extra => l_dump);
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_character_codes ( p_text text, p_scope logger_logs.scope%type default null, p_show_common_codes boolean default true, p_level logger_logs.logger_level%type default null) FROM PUBLIC;

--
-- dblink wrapper to call function logger_log_apex_items as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_log_apex_items ( p_text text default 'Log APEX Items', p_scope logger_logs.scope%type default null, p_item_type text default logger.g_apex_item_type_all, p_log_null_items boolean default true, p_level logger_logs.logger_level%type default null) AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_log_apex_items_atx ( ' || quote_nullable(p_text) || ',' || quote_nullable(p_scope) || ',' || quote_nullable(p_item_type) || ',' || quote_nullable(p_log_null_items) || ',' || quote_nullable(p_level) || ' )';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;



  /**
   * Log's APEX items
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #115 Only log not-null values
   *  - #29 Support for definging level
   *  - #54: Add p_item_type
   *
   * @author Tyler Muth
   * @created ???
   * @param p_text
   * @param p_scope
   * @param p_item_type Either the g_apex_item_type_... type or just the APEX page number for a specific page.
   * @param p_log_null_items If set to false, null values won't be logged
   * @param p_level Highest level to run at (default logger.g_debug). Example. If you set to logger.g_error it will work when both in DEBUG and ERROR modes. However if set to logger.g_debug(default) will not store values when level is set to ERROR.
   */
CREATE OR REPLACE PROCEDURE logger_log_apex_items_atx ( p_text text default 'Log APEX Items', p_scope logger_logs.scope%type default null, p_item_type text default logger.g_apex_item_type_all, p_log_null_items boolean default true, p_level logger_logs.logger_level%type default null) AS $body$
DECLARE

    l_error varchar(4000);
BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(coalesce(p_level, logger.g_debug)) then

        $if $$apex $then
          -- Validate p_item_type
          CALL logger_assert(
            p_condition => upper(p_item_type) in (logger.g_apex_item_type_all, logger.g_apex_item_type_app, logger.g_apex_item_type_page) or logger_is_number(p_item_type),
            p_message => logger_sprintf('APEX Item Scope was set to %s. Must be %s, %s, %s, or page number', p_item_type, logger.g_apex_item_type_all, logger.g_apex_item_type_page, logger.g_apex_item_type_page));

          CALL logger_log_internal(
            p_text => p_text,
            p_log_level => coalesce(p_level, logger.g_apex),
            p_scope => p_scope);

          CALL logger_snapshot_apex_items(
            p_log_id => current_setting('logger.g_log_id')::bigint,
            p_item_type => upper(p_item_type),
            p_log_null_items => p_log_null_items);
        $else
          l_error := 'Error! Logger is not configured for APEX yet. ';

          CALL logger_log_internal(
            p_text => l_error,
            p_log_level => logger.g_apex,
            p_scope => p_scope);
        $end
      end if;
    $END;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_log_apex_items ( p_text text default 'Log APEX Items', p_scope logger_logs.scope%type default null, p_item_type text default logger.g_apex_item_type_all, p_log_null_items boolean default true, p_level logger_logs.logger_level%type default null) FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_log_apex_items_atx ( p_text text default 'Log APEX Items', p_scope logger_logs.scope%type default null, p_item_type text default logger.g_apex_item_type_all, p_log_null_items boolean default true, p_level logger_logs.logger_level%type default null) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #73/#75: Use localtimestamp
   *
   * @author Tyler Muth
   * @created ???
   * @param p_unit
   * @param p_log_in_table
   */
CREATE OR REPLACE PROCEDURE logger_time_start ( p_unit text, p_log_in_table boolean default true) AS $body$
DECLARE

    l_proc_name varchar(100);
    l_text varchar(4000);
    l_pad varchar(100);

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        PERFORM set_config('logger.g_running_timers', current_setting('logger.g_running_timers')::integer + 1, false);

        if current_setting('logger.g_running_timers')::integer > 1 then
          -- Use 'a' since lpad requires a value to pad
          l_pad := replace(lpad('a',current_setting('logger.g_running_timers')::integer,'>')||' ', 'a', null);
        end if;

        current_setting('logger.g_proc_start_times')::ts_array(p_unit) := localtimestamp;

        l_text := l_pad||'START: '||p_unit;

        if p_log_in_table then
           := logger_ins_logger_logs(
            p_unit_name => p_unit, p_logger_level => g_timing, p_text =>l_text, po_id => current_setting('logger.g_log_id')::bigint);
        end if;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_time_start ( p_unit text, p_log_in_table boolean default true) FROM PUBLIC;

  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #73: Remove additional timer decrement since it was already happening in function time_stop
   *
   * @author Tyler Muth
   * @created ???
   * @param p_scope
   * @param p_unit
   */
CREATE OR REPLACE PROCEDURE logger_time_stop ( p_unit text, p_scope text default null) AS $body$
DECLARE

    l_time_string varchar(50);
    l_text varchar(4000);
    l_pad varchar(100);

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        if current_setting('logger.g_proc_start_times')::ts_array.exists(p_unit) then

          if current_setting('logger.g_running_timers')::integer > 1 then
            -- Use 'a' since lpad requires a value to pad
            l_pad := replace(lpad('a',current_setting('logger.g_running_timers')::integer,'>')||' ', 'a', null);
          end if;

          --l_time_string := rtrim(regexp_replace(systimestamp-(g_proc_start_times(p_unit)),'.+?[[:space:]](.*)','\1',1,0),0);
          -- Function time_stop will decrement the timers and pop the name from the g_proc_start_times array
          l_time_string := logger_time_stop(
            p_unit => p_unit,
            p_log_in_table => false);

          l_text := l_pad||'STOP : '||p_unit ||' - '||l_time_string;

           := logger_ins_logger_logs(
            p_unit_name => p_unit, p_scope => p_scope, p_logger_level => g_timing, p_text =>l_text, po_id => current_setting('logger.g_log_id')::bigint);
        end if;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_time_stop ( p_unit text, p_scope text default null) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #73/#75: Trim timezone from systimestamp to localtimestamp
   *
   * @author Tyler Muth
   * @created ???
   * @param p_unit
   * @param p_scope
   * @param p_log_in_table
   * @return Timer string
   */
CREATE OR REPLACE FUNCTION logger_time_stop ( p_unit text, p_scope text default null, p_log_in_table boolean default true) RETURNS varchar AS $body$
DECLARE

    l_time_string varchar(50);

BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        if current_setting('logger.g_proc_start_times')::ts_array.exists(p_unit) then

          l_time_string := rtrim(regexp_replace(localtimestamp - (current_setting('logger.g_proc_start_times')::ts_array(p_unit)),'.+?[[:space:]](.*)','\1',1,0),0);

          current_setting('logger.g_proc_start_times')::ts_array.delete(p_unit);
          PERFORM set_config('logger.g_running_timers', current_setting('logger.g_running_timers')::integer - 1, false);

          if p_log_in_table then
             := logger_ins_logger_logs(
              p_unit_name => p_unit, p_scope => p_scope, p_logger_level => g_timing, p_text => l_time_string, po_id => current_setting('logger.g_log_id')::bigint);
          end if;

          return l_time_string;

        end if;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_time_stop ( p_unit text, p_scope text default null, p_log_in_table boolean default true) FROM PUBLIC;


  /**
   *
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #73/#75: Trim timezone from systimestamp to localtimestamp
   *
   * @author Tyler Muth
   * @created ???
   * @param p_unit
   * @param p_scope
   * @param p_log_in_table
   * @return Timer in seconds
   */
CREATE OR REPLACE FUNCTION logger_time_stop_seconds ( p_unit text, p_scope text default null, p_log_in_table boolean default true) RETURNS bigint AS $body$
DECLARE

    l_time_string varchar(50);
    l_seconds bigint;
    l_interval interval day to second;


BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        if current_setting('logger.g_proc_start_times')::ts_array.exists(p_unit) then
          l_interval := localtimestamp - (current_setting('logger.g_proc_start_times')::ts_array(p_unit));
          l_seconds := extract(day from l_interval) * 86400 + extract(hour from l_interval) * 3600 + extract(minute from l_interval) * 60 + extract(second from l_interval);

          current_setting('logger.g_proc_start_times')::ts_array.delete(p_unit);
          PERFORM set_config('logger.g_running_timers', current_setting('logger.g_running_timers')::integer - 1, false);

          if p_log_in_table then
             := logger_ins_logger_logs(
              p_unit_name => p_unit, p_scope => p_scope, p_logger_level => g_timing, p_text => l_seconds, po_id => current_setting('logger.g_log_id')::bigint);
          end if;

          return l_seconds;

        end if;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_time_stop_seconds ( p_unit text, p_scope text default null, p_log_in_table boolean default true) FROM PUBLIC;


  /**
   * Resets all timers
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   */
CREATE OR REPLACE PROCEDURE logger_time_reset () AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      if logger_ok_to_log(logger.g_debug) then
        PERFORM set_config('logger.g_running_timers', 0, false);
        current_setting('logger.g_proc_start_times')::ts_array.delete;
      end if;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_time_reset () FROM PUBLIC;

  /**
   * Returns Global or User preference
   * User preference is only valid for LEVEL and INCLUDE_CALL_STACK
   *  - If a user setting exists, it will be returned, if not the system level preference will be return
   *
   * Updates
   *  - 2.0.0: Added user preference support
   *  - 2.1.2: Fixed issue when calling set_level with the same client_id multiple times
   *
   * Related Tickets:
   *  - #127: Added logger_prefs.pref_type
   *
   * @author Tyler Muth
   * @created ???
   *
   * @param p_pref_name
   * @param p_pref_type Namespace for preference
   */
CREATE OR REPLACE FUNCTION logger_get_pref ( p_pref_name logger_prefs.pref_name%type, p_pref_type logger_prefs.pref_type%type default logger.g_pref_type_logger) RETURNS varchar AS $body$
DECLARE
 null or not $$no_op $then
        relies_on(logger_prefs, logger_prefs_by_client_id)
      $end
    $end
  is
    l_scope varchar(30) := 'get_pref';
    l_pref_value logger_prefs.pref_value%type;
    l_client_id logger_prefs_by_client_id.client_id%type;
    l_pref_name logger_prefs.pref_name%type := upper(p_pref_name);
    l_pref_type logger_prefs.pref_type%type := upper(p_pref_type);

BEGIN

    $if $$no_op $then
      return null;
    $else
      $if $$logger_debug $then
        RAISE NOTICE '% select pref', l_scope;
      $end

      l_client_id := sys_context('userenv','client_identifier');

      select pref_value
      into STRICT l_pref_value
      from (
        SELECT pref_value, row_number() over (order by rank) rn
        from (
          -- Client specific logger levels trump system level logger level
          SELECT
            case
              when l_pref_name = current_setting('logger.gc_pref_level')::logger_prefs.pref_name%type then logger_level
              when l_pref_name = current_setting('logger.gc_pref_include_call_stack')::logger_prefs.pref_name%type then include_call_stack
            end pref_value,
            1 rank
          from logger_prefs_by_client_id
          where 1=1
            and client_id = l_client_id
            -- Only try to get prefs at a client level if pref is in LEVEL or INCLUDE_CALL_STACK
            and (l_client_id IS NOT NULL AND l_client_id::text <> '')
            -- #127
            -- Prefs by client aren't available for custom prefs right now
            -- Only need to search this table if p_pref_type is LOGGER
            and l_pref_type = logger.g_pref_type_logger
            and l_pref_name in (current_setting('logger.gc_pref_level')::logger_prefs.pref_name%type, current_setting('logger.gc_pref_include_call_stack')::logger_prefs.pref_name%type)
          
union

          -- System level configuration
          select pref_value, 2 rank
          from logger_prefs
          where 1=1
            and pref_name = l_pref_name
            and pref_type = l_pref_type
        ) alias8 
      ) alias9 
      where rn = 1;
      return l_pref_value;
    $end

  exception
    when no_data_found then
      return null;
    when others then
      raise;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_get_pref ( p_pref_name logger_prefs.pref_name%type, p_pref_type logger_prefs.pref_type%type default logger.g_pref_type_logger) FROM PUBLIC;


  /**
   * Sets a preference
   * If it does not exist, it will insert one
   *
   * Notes:
   *  - Does not support setting system preferences
   *
   * Related Tickets:
   *  - #127
   *
   * @author Alex Nuijten / Martin D'Souza
   * @created 24-APR-2015
   * @param p_pref_type
   * @param p_pref_name
   * @param p_pref_value
   */
CREATE OR REPLACE PROCEDURE logger_set_pref ( p_pref_type logger_prefs.pref_type%type, p_pref_name logger_prefs.pref_name%type, p_pref_value logger_prefs.pref_value%type) AS $body$
DECLARE

    l_pref_type logger_prefs.pref_type%type := trim(both upper(p_pref_type));
    l_pref_name logger_prefs.pref_name%type := trim(both upper(p_pref_name));

BEGIN

    $if $$no_op $then
      null;
    $else
      if l_pref_type = logger.g_pref_type_logger then
        RAISE EXCEPTION '%', 'Can not set ' || l_pref_type || '. Reserved for Logger' USING ERRCODE = '45001';
      end if;

      merge into logger_prefs p
      using(SELECT l_pref_type pref_type, l_pref_name pref_name, p_pref_value pref_value
             ) args
      on ( 1=1
        and p.pref_type = args.pref_type
        and p.pref_name = args.pref_name)
      when matched then
        update
        set p.pref_value =  args.pref_value
      when not matched then
        insert(pref_type, pref_name ,pref_value)
      values (args.pref_type, args.pref_name ,args.pref_value);
    $end  -- $no_op
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_set_pref ( p_pref_type logger_prefs.pref_type%type, p_pref_name logger_prefs.pref_name%type, p_pref_value logger_prefs.pref_value%type) FROM PUBLIC;

  /**
   * Removes a Preference
   *
   * Notes:
   *  - Does not support setting system preferences
   *
   * Related Tickets:
   *  - #127
   *
   * @author Alex Nuijten / Martin D'Souza
   * @created 30-APR-2015
   *
   * @param p_pref_type
   * @param p_pref_name
   */
CREATE OR REPLACE PROCEDURE logger_del_pref ( p_pref_type logger_prefs.pref_type%type, p_pref_name logger_prefs.pref_name%type) AS $body$
DECLARE

    l_pref_type logger_prefs.pref_type%type := trim(both upper(p_pref_type));
    l_pref_name logger_prefs.pref_name%type := trim(both upper(p_pref_name));

BEGIN
    $if $$no_op $then
      null;
    $else
      if l_pref_type = logger.g_pref_type_logger then
        RAISE EXCEPTION '%', 'Can not delete ' || l_pref_type || '. Reserved for Logger' USING ERRCODE = '45001';
      end if;

      delete from logger_prefs
      where 1=1
        and pref_type = l_pref_type
        and pref_name = l_pref_name;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_del_pref ( p_pref_type logger_prefs.pref_type%type, p_pref_name logger_prefs.pref_name%type) FROM PUBLIC;

--
-- dblink wrapper to call function logger_purge as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_purge ( p_purge_after_days bigint default null, p_purge_min_level bigint DEFAULT NULL) AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_purge_atx ( ' || quote_nullable(p_purge_after_days) || ',' || quote_nullable(p_purge_min_level) || ' )';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;



  /**
   * Purges logger_logs data
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  - #48 Support for overloading
   *
   * @author Martin D'Souza
   * @created 14-Jun-2014
   * @param p_purge_after_days
   * @param p_purge_min_level
   */
CREATE OR REPLACE PROCEDURE logger_purge_atx ( p_purge_after_days bigint default null, p_purge_min_level bigint DEFAULT NULL) AS $body$
DECLARE

    $if $$coalesce(no_op::text, '') = '' or not $$no_op $then
      l_purge_after_days bigint := coalesce(p_purge_after_days,logger_get_pref(logger.gc_pref_purge_after_days));
    $end;
BEGIN
    $if $$no_op $then
      null;
    $else

      if admin_security_check then
        delete
          from logger_logs
         where logger_level >= p_purge_min_level
           and time_stamp < statement_timestamp() - (l_purge_after_days * ('1'||'day')::interval)
           and logger_level > g_permanent;
      end if;
    $END;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_purge ( p_purge_after_days bigint default null, p_purge_min_level bigint DEFAULT NULL) FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_purge_atx ( p_purge_after_days bigint default null, p_purge_min_level bigint DEFAULT NULL) FROM PUBLIC;


  /**
   * Wrapper for logger_purge(to accept number for purge_min_level)
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   * @param p_purge_after_days
   * @param p_purge_min_level
   */
CREATE OR REPLACE PROCEDURE logger_purge ( p_purge_after_days text default null, p_purge_min_level text default null) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      CALL logger_purge(
        p_purge_after_days => (p_purge_after_days)::numeric ,
        p_purge_min_level => logger_convert_level_char_to_num(coalesce(p_purge_min_level,logger_get_pref(current_setting('logger.gc_pref_purge_min_level')::logger_prefs.pref_name%type))));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_purge ( p_purge_after_days text default null, p_purge_min_level text default null) FROM PUBLIC;

--
-- dblink wrapper to call function logger_purge_all as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_purge_all () AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_purge_all_atx ()';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;



  /**
   * Purges all records that aren't marked as permanent
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   */
CREATE OR REPLACE PROCEDURE logger_purge_all_atx () AS $body$
DECLARE

    l_purge_level bigint  := g_permanent;
BEGIN
    $if $$no_op $then
      null;
    $else
      if admin_security_check then
        delete from logger_logs where logger_level > l_purge_level;
      end if;
    $END;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_purge_all () FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_purge_all_atx () FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_display_output ( p_name text, p_value text) AS $body$
BEGIN
      if l_output_format = 'SQL-DEVELOPER' then
        RAISE NOTICE '<pre>%: <strong>%</strong></pre>', rpad(p_name,25), p_value;
      elsif l_output_format = 'HTTP' then
        htp.p('<br />'||p_name||': <strong>'||p_value||'</strong>');
      else
        RAISE NOTICE '%: %', rpad(p_name,25), p_value;
      end if;
    END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_display_output ( p_name text, p_value text) FROM PUBLIC;

--
-- dblink wrapper to call function logger_unset_client_level as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_unset_client_level (p_client_id text) AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_unset_client_level_atx ( ' || quote_nullable(p_client_id) || ' )';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;



  /**
   * Unsets a logger level for a given client_id
   * This will only unset for client specific logger levels
   * Note: An explicit commit will occur in this procedure
   *
   * @author Martin D'Souza
   * @created 6-Apr-2013
   *
   * @param p_client_id Client identifier (case sensitive) to unset logger level in.
   */
CREATE OR REPLACE PROCEDURE logger_unset_client_level_atx (p_client_id text) AS $body$
BEGIN
    $if $$no_op $then
      null;
    $else
      CALL logger_assert((p_client_id IS NOT NULL AND p_client_id::text <> ''), 'p_client_id is a required value');

      -- Remove from client specific table
      delete from logger_prefs_by_client_id
      where client_id = p_client_id;

      -- Remove context values
      dbms_session.clear_context(
       namespace => g_context_name,
       client_id => p_client_id,
       attribute => current_setting('logger.gc_ctx_attr_level')::varchar(5));

      dbms_session.clear_context(
       namespace => g_context_name,
       client_id => p_client_id,
       attribute => current_setting('logger.gc_ctx_attr_include_call_stack')::varchar(18));

    $END;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_unset_client_level (p_client_id text) FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_unset_client_level_atx (p_client_id text) FROM PUBLIC;


  /**
   * Unsets client_level that are stale (i.e. past thier expiry date)
   *
   * @author Martin D'Souza
   * @created 7-Apr-2013
   *
   * @param p_unset_after_hours If null then preference UNSET_CLIENT_ID_LEVEL_AFTER_HOURS
   */
CREATE OR REPLACE PROCEDURE logger_unset_client_level () AS $body$
DECLARE


  x RECORD;

BEGIN
    $if $$no_op $then
      null;
    $else
      for x in (
        SELECT client_id
        from logger_prefs_by_client_id
        where clock_timestamp() > expiry_date ) loop

        CALL logger_unset_client_level(p_client_id => x.client_id);
      end loop;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_unset_client_level () FROM PUBLIC;


  /**
   * Unsets all client specific preferences
   * An implicit commit will occur as unset_client_level makes a commit
   *
   * @author Martin D'Souza
   * @created 7-Apr-2013
   *
   */
CREATE OR REPLACE PROCEDURE logger_unset_client_level_all () AS $body$
DECLARE


  x RECORD;

BEGIN
    $if $$no_op $then
      null;
    $else
      for x in (SELECT client_id from logger_prefs_by_client_id) loop
        CALL logger_unset_client_level(p_client_id => x.client_id);
      end loop;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_unset_client_level_all () FROM PUBLIC;


  /**
   * Displays commonly used dbms_output SQL*Plus settings
   *
   * Notes:
   *  -
   *
   * Related Tickets:
   *  -
   *
   * @author Tyler Muth
   * @created ???
   */
CREATE OR REPLACE PROCEDURE logger_sqlplus_format () AS $body$
BEGIN
    EXECUTE 'begin dbms_output.enable(1000000); end;';
    RAISE NOTICE 'set linesize 200';
    RAISE NOTICE 'set pagesize 100';

    RAISE NOTICE 'column id format 999999';
    RAISE NOTICE 'column text format a75';
    RAISE NOTICE 'column call_stack format a100';
    RAISE NOTICE 'column extra format a100';

  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_sqlplus_format () FROM PUBLIC;

  /**
   * Converts parameter to varchar2
   *
   * Notes:
   *  - As this function could be useful for non-logging purposes will not apply a NO_OP to it for conditional compilation
   *  - Need to call this tochar instead of to_char since there will be a conflict when calling it
   *
   * Related Tickets:
   *  - #68
   *
   * @author Martin D'Souza
   * @created 07-Jun-2014
   * @param p_value
   * @return varchar2 value for p_value
   */
CREATE OR REPLACE FUNCTION logger_tochar ( p_val bigint) RETURNS varchar AS $body$
BEGIN
    return p_val::text;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val bigint) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_tochar ( p_val timestamp(0)) RETURNS varchar AS $body$
BEGIN
    return to_char(p_val, current_setting('logger.gc_date_format')::varchar(255));
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val timestamp(0)) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_tochar ( p_val timestamp) RETURNS varchar AS $body$
BEGIN
    return to_char(p_val, current_setting('logger.gc_timestamp_format')::varchar(255)current_setting('logger.gc_date_format')::varchar(255)||);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val timestamp) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_tochar ( p_val timestamp with time zone) RETURNS varchar AS $body$
BEGIN
    return to_char(p_val, current_setting('logger.gc_timestamp_tz_format')::varchar(255)gc_timestamp_format||);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val timestamp with time zone) FROM PUBLIC;



CREATE OR REPLACE FUNCTION logger_tochar ( p_val timestamp with time zone) RETURNS varchar AS $body$
BEGIN
    return to_char(p_val, current_setting('logger.gc_timestamp_tz_format')::varchar(255)gc_timestamp_format||);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val timestamp with time zone) FROM PUBLIC;

  -- #119: Return null for null booleans
CREATE OR REPLACE FUNCTION logger_tochar ( p_val boolean) RETURNS varchar AS $body$
BEGIN
    return case p_val when true then 'TRUE' when false then 'FALSE' else null end;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_tochar ( p_val boolean) FROM PUBLIC;



  -- Handle Parameters
  /**
   * Append parameter to table of parameters
   * Nothing is actually logged in this procedure
   * This procedure is overloaded
   *
   * Related Tickets:
   *  - #67: Updated to reference to_char functions
   *
   * @author Martin D'Souza
   * @created 19-Jan-2013
   *
   * @param p_params Table of parameters (param will be appended to this)
   * @param p_name Name
   * @param p_val Value in its format. Will be converted to string
   */
CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val text ) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      l_param.name := p_name;
      l_param.val := p_val;
      p_params(p_params.count + 1) := l_param;
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val text ) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val bigint) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val bigint) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp(0)) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp(0)) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp with time zone) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp with time zone) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp with time zone) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val timestamp with time zone) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val boolean) AS $body$
DECLARE

    l_param logger.rec_param;

BEGIN
    $if $$no_op $then
      null;
    $else
      p_params := logger_append_param(p_params => p_params, p_name => p_name, p_val => logger_tochar(p_val => p_val));
    $end
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_append_param ( p_params INOUT logger.tab_param, p_name text, p_val boolean) FROM PUBLIC;

--
-- dblink wrapper to call function logger_ins_logger_logs as an autonomous transaction
--
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE PROCEDURE logger_ins_logger_logs ( p_logger_level logger_logs.logger_level%type, p_text text default null, -- Not using type since want to be able to pass in 32767 characters
 p_scope logger_logs.scope%type default null, p_call_stack logger_logs.call_stack%type default null, p_unit_name logger_logs.unit_name%type default null, p_line_no logger_logs.line_no%type default null, p_extra logger_logs.extra%type default null, po_id INOUT logger_logs.id%type  DEFAULT NULL) AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
	v_query     text;

BEGIN
	v_query := 'CALL logger_ins_logger_logs_atx ( ' || quote_nullable(p_logger_level) || ',' || quote_nullable(p_text) || ',' || quote_nullable(
) || ',' || quote_nullable(p_call_stack) || ',' || quote_nullable(p_unit_name) || ',' || quote_nullable(p_line_no) || ',' || quote_nullable(p_extra) || ',' || quote_nullable(po_id) || ' )';
	SELECT v_ret INTO po_id FROM dblink(v_conn_str, v_query) AS p (v_ret NULL);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;



  /**
   * Handles inserts into LOGGER_LOGS.
   *
   * Replaces trigger for both performance issues and to be a single location for all insert statements
   *
   * autonomous_transaction so commit will be performed after insert
   *
   * @author Martin D'Souza
   * @created 30-Jul-2013
   *
   * Related Issues
   *  - #31: Initial ticket
   *  - #51: Added SID column
   *  - #70: Fixed missing no_op flag
   *  - #109: Fix length check for multibyte characters
   *
   * @param p_logger_level
   * @param p_text
   * @param p_scope
   * @param p_call_stack
   * @param p_unit_name
   * @param p_line_no
   * @param p_extra
   * @param po_id ID entered into logger_logs for this record
   */
CREATE OR REPLACE PROCEDURE logger_ins_logger_logs_atx ( p_logger_level logger_logs.logger_level%type, p_text text default null,
 p_scope logger_logs.scope%type default null, p_call_stack logger_logs.call_stack%type default null, p_unit_name logger_logs.unit_name%type default null, p_line_no logger_logs.line_no%type default null, p_extra logger_logs.extra%type default null, po_id INOUT logger_logs.id%type  DEFAULT NULL) AS $body$
DECLARE
l_id logger_logs.id%type;
    l_text varchar(32767) := p_text;
    l_extra logger_logs.extra%type := p_extra;
    l_tmp_clob text;


BEGIN
    $if $$no_op $then
      null;
    $else
      -- Using select into to support version older than 11gR1 (see Issue 26)
      select nextval('logger_logs_seq')
      into STRICT po_id
;

      -- 2.1.0: If text is > 4000 characters, it will be moved to the EXTRA column (Issue 17)
      $if $$large_text_column $then  -- Only check for moving to Clob if small text column
        -- Don't do anything since column supports large text
      $else
        if lengthb(l_text) > 4000 then  -- #109 Using lengthb for multibyte characters
          if coalesce(l_extra::text, '') = '' then
            l_extra := l_text;
          else
            -- Using temp clob for performance purposes: http://www.talkapex.com/2009/06/how-to-quickly-append-varchar2-to-clob.html
            l_tmp_clob := current_setting('logger.gc_line_feed')::varchar(1) || current_setting('logger.gc_line_feed')::varchar(1) || '*** Content moved from TEXT column ***' || current_setting('logger.gc_line_feed')::varchar(1);
            l_extra := l_extra || l_tmp_clob;
            l_tmp_clob := l_text;
            l_extra := l_extra || l_text;
          end if; -- l_extra is not null
          l_text := 'Text moved to EXTRA column';
        end if; -- length(l_text)
      $end

      insert into logger_logs(
        id, logger_level, text,
        time_stamp, scope, module,
        action,
        user_name,
        client_identifier,
        call_stack, unit_name, line_no ,
        scn,
        extra,
        sid,
        client_info
        )
       values (
         po_id, p_logger_level, l_text,
         statement_timestamp(), lower(p_scope), sys_context('userenv','module'),
         sys_context('userenv','action'),
         coalesce($if $$apex $then apex_application.g_user $else user $end,user),
         sys_context('userenv','client_identifier'),
         p_call_stack, upper(p_unit_name), p_line_no,
         null,
         l_extra,
         (sys_context('userenv','sid'))::numeric ,
         sys_context('userenv','client_info')
         );

    $end  -- $$NO_OP
    commit;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE logger_ins_logger_logs ( p_logger_level logger_logs.logger_level%type, p_text text default null, p_scope logger_logs.scope%type default null, p_call_stack logger_logs.call_stack%type default null, p_unit_name logger_logs.unit_name%type default null, p_line_no logger_logs.line_no%type default null, p_extra logger_logs.extra%type default null, po_id INOUT logger_logs.id%type  DEFAULT NULL) FROM PUBLIC; -- REVOKE ALL ON PROCEDURE logger_ins_logger_logs_atx ( p_logger_level logger_logs.logger_level%type, p_text text default null, p_scope logger_logs.scope%type default null, p_call_stack logger_logs.call_stack%type default null, p_unit_name logger_logs.unit_name%type default null, p_line_no logger_logs.line_no%type default null, p_extra logger_logs.extra%type default null, po_id INOUT logger_logs.id%type  DEFAULT NULL) FROM PUBLIC;


  /**
   * Does string replacement similar to C's sprintf
   *
   * Notes:
   *  - Uses the following replacement algorithm (in following order)
   *    - Replaces %s<n> with p_s<n>
   *    - Occurrences of %s (no number) are replaced with p_s1..p_s10 in order that they appear in text
   *    - %% is escaped to %
   *  - As this function could be useful for non-logging purposes will not apply a NO_OP to it for conditional compilation
   *
   * Related Tickets:
   *  - #32: Also see #59
   *  - #95: Remove no_op clause
   *
   * @author Martin D'Souza
   * @created 15-Jun-2014
   * @param p_str Messsage to format using %s and %d replacement strings
   * @param p_s1
   * @param p_s2
   * @param p_s3
   * @param p_s4
   * @param p_s5
   * @param p_s6
   * @param p_s7
   * @param p_s8
   * @param p_s9
   * @param p_s10
   * @return p_msg with strings replaced
   */
CREATE OR REPLACE FUNCTION logger_sprintf ( p_str text, p_s1 text default null, p_s2 text default null, p_s3 text default null, p_s4 text default null, p_s5 text default null, p_s6 text default null, p_s7 text default null, p_s8 text default null, p_s9 text default null, p_s10 text default null) RETURNS varchar AS $body$
DECLARE

    l_return varchar(4000);
    c_substring_regexp constant varchar(10) := '%s';


BEGIN
    l_return := p_str;

    -- Replace %s<n> with p_s<n>``
    for i in 1..10 loop
      l_return := regexp_replace(l_return, c_substring_regexp || i,
        case
          when i = 1 then p_s1
          when i = 2 then p_s2
          when i = 3 then p_s3
          when i = 4 then p_s4
          when i = 5 then p_s5
          when i = 6 then p_s6
          when i = 7 then p_s7
          when i = 8 then p_s8
          when i = 9 then p_s9
          when i = 10 then p_s10
          else null
        end,
        1,0,'c', 'g');
    end loop;

    $if $$logger_debug $then
      RAISE NOTICE 'Before utl_lms: %', l_return;
    $end

    -- Replace any occurences of %s with p_s<n> (in order) and escape %% to %
    l_return := utl_lms.format_message(l_return,p_s1, p_s2, p_s3, p_s4, p_s5, p_s6, p_s7, p_s8, p_s9, p_s10);

    return l_return;

  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_sprintf ( p_str text, p_s1 text default null, p_s2 text default null, p_s3 text default null, p_s4 text default null, p_s5 text default null, p_s6 text default null, p_s7 text default null, p_s8 text default null, p_s9 text default null, p_s10 text default null) FROM PUBLIC;


  /**
   * Returns the rec_logger_logs for given logger_level
   * Used for plugin.
   * Not meant to be called by general public, and thus not documented
   *
   * Notes:
   *  - -- FUTURE mdsouza: Add tests for this (#86)
   *
   * Related Tickets:
   *  - #46
   *
   * @author Martin D'Souza
   * @created 11-Mar-2015
   * @param p_logger_level Logger level of plugin wanted to return
   * @return Logger rec based on plugin type
   */
CREATE OR REPLACE FUNCTION logger_get_plugin_rec ( p_logger_level logger_logs.logger_level%type) RETURNS LOGGER.REC_LOGGER_LOG AS $body$
BEGIN

    if p_logger_level = logger.g_error then
      return current_setting('logger.g_plug_logger_log_error')::rec_logger_log;
    end if;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION logger_get_plugin_rec ( p_logger_level logger_logs.logger_level%type) FROM PUBLIC;
-- End of Oracle package 'logger' declaration

-- Total size of package code: 80368 bytes.
-- Total size of package code without comments and header: 20805 bytes.
-- Detailed cost per function:
	-- Function logger.append_cgi_env total estimated cost: 3.4
		-- CONCAT => 4 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.append_ctx total estimated cost: 4.8
		-- CONCAT => 8 (cost: 0.1)
		-- TEST => 2
		-- Sys_Context => 1
		-- SIZE => 1
	-- Function logger.append_param total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.assert total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.convert_level_char_to_num total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.convert_level_num_to_char total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.date_text_format total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.date_text_format_base total estimated cost: 6
		-- CONCAT => 8 (cost: 0.1)
		-- TRUNC => 2 (cost: 0.1)
		-- MONTHS_BETWEEN => 2 (cost: 1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.del_pref total estimated cost: 3.2
		-- CONCAT => 2 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.display_output total estimated cost: 4.4
		-- CONCAT => 10 (cost: 0.1)
		-- TEST => 2
		-- HTP => 2 (cost: 0.2)
		-- SIZE => 1
	-- Function logger.f_get_set_global_context total estimated cost: 6.1
		-- TEST => 2
		-- CTX_ => 1 (cost: 3)
		-- CONCAT => 1 (cost: 0.1)
		-- SIZE => 1
	-- Function logger.get_character_codes total estimated cost: 4.8
		-- CONCAT => 8 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
		-- Dump => 1
	-- Function logger.get_debug_info total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.get_level_number total estimated cost: 3.1
		-- TEST => 2
		-- CONCAT => 1 (cost: 0.1)
		-- SIZE => 1
	-- Function logger.get_param_clob total estimated cost: 3.4
		-- CONCAT => 4 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.get_plugin_rec total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.get_pref total estimated cost: 4.1
		-- TEST => 2
		-- Sys_Context => 1
		-- CONCAT => 1 (cost: 0.1)
		-- SIZE => 1
	-- Function logger.include_call_stack total estimated cost: 10
		-- CTX_ => 2 (cost: 3)
		-- TEST => 2
		-- Sys_Context => 1
		-- SIZE => 1
	-- Function logger.ins_logger_logs total estimated cost: 4.6
		-- CONCAT => 5 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
		-- Sys_Context => 1
		-- TO_NUMBER => 1 (cost: 0.1)
	-- Function logger.is_number total estimated cost: 3.1
		-- TEST => 2
		-- TO_NUMBER => 1 (cost: 0.1)
		-- SIZE => 1
	-- Function logger.log total estimated cost: 6
		-- TEST => 2
		-- DBMS_ => 1 (cost: 3)
		-- SIZE => 1
	-- Function logger.log_apex_items total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_cgi_env total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_character_codes total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_error total estimated cost: 15.5
		-- CONCAT => 5 (cost: 0.1)
		-- DBMS_ => 4 (cost: 3)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_info total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_information total estimated cost: 6
		-- TEST => 2
		-- DBMS_ => 1 (cost: 3)
		-- SIZE => 1
	-- Function logger.log_internal total estimated cost: 3.1
		-- TEST => 2
		-- SIZE => 1
		-- CONCAT => 1 (cost: 0.1)
	-- Function logger.log_permanent total estimated cost: 6
		-- TEST => 2
		-- SIZE => 1
		-- DBMS_ => 1 (cost: 3)
	-- Function logger.log_warn total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.log_warning total estimated cost: 6
		-- TEST => 2
		-- SIZE => 1
		-- DBMS_ => 1 (cost: 3)
	-- Function logger.ok_to_log total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.purge total estimated cost: 3.1
		-- TEST => 2
		-- SIZE => 1
		-- TO_NUMBER => 1 (cost: 0.1)
	-- Function logger.purge_all total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.save_global_context total estimated cost: 6
		-- TEST => 2
		-- DBMS_ => 1 (cost: 3)
		-- SIZE => 1
	-- Function logger.set_extra_with_params total estimated cost: 3.6
		-- CONCAT => 6 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.set_pref total estimated cost: 3.2
		-- CONCAT => 2 (cost: 0.1)
		-- TEST => 2
		-- MERGE => 1
		-- SIZE => 1
	-- Function logger.snapshot_apex_items total estimated cost: 3.1
		-- TEST => 2
		-- TO_NUMBER => 1 (cost: 0.1)
		-- SIZE => 1
	-- Function logger.sprintf total estimated cost: 6.2
		-- CONCAT => 2 (cost: 0.1)
		-- TEST => 2
		-- UTL_ => 1 (cost: 3)
		-- SIZE => 1
	-- Function logger.sqlplus_format total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.start_stop_plugin total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.time_reset total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.time_start total estimated cost: 3.3
		-- CONCAT => 3 (cost: 0.1)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.time_stop total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.time_stop_seconds total estimated cost: 27
		-- EXTRACT => 8 (cost: 3)
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.tochar total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.unset_client_level total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
	-- Function logger.unset_client_level_all total estimated cost: 3
		-- TEST => 2
		-- SIZE => 1
-- Total estimated cost for package logger: 225.1 units, 3 person-day(s)
