-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE gx_jt_nested (p_count OUT bigint) AS $body$
DECLARE

  v_count bigint;

BEGIN
  SELECT COUNT(*) INTO STRICT v_count
  FROM JSON_TABLE(
      '{"order":1,"items":[{"sku":"a"},{"sku":"b"},{"sku":"c"}]}',
      '$'
      COLUMNS(
          order_id bigint PATH '$.order',
          NESTED PATH '$.items[*]' COLUMNS(sku varchar(10) PATH '$.sku')
      )
  );
  p_count := v_count;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_jt_nested (p_count OUT bigint) FROM PUBLIC;





CREATE OR REPLACE PROCEDURE gx_jt_onerror (p_count OUT bigint) AS $body$
DECLARE

  v_count bigint;

BEGIN
  SELECT COUNT(*) INTO STRICT v_count
  FROM JSON_TABLE(
      '[{"id":1},{"id":2}]',
      '$[*]' ERROR ON ERROR
      COLUMNS(id bigint PATH '$.id')
  );
  p_count := v_count;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_jt_onerror (p_count OUT bigint) FROM PUBLIC;


