-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE gx_jt (p_count OUT bigint) AS $body$
DECLARE

  v_count bigint;

BEGIN
  SELECT COUNT(*) INTO STRICT v_count
  FROM JSON_TABLE(
      '[{"id":1,"amount":100},{"id":2,"amount":200}]',
      '$[*]'
      COLUMNS(
          id     bigint PATH '$.id',
          amount bigint PATH '$.amount'
      )
  );
  p_count := v_count;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_jt (p_count OUT bigint) FROM PUBLIC;


