from ora2pg_gap_report.detectors.virtual_column import find_virtual_columns


def test_full_form_generated_always_as_virtual_is_flagged():
    source = (
        "create table employees (\n"
        "  emp_id number,\n"
        "  salary number,\n"
        "  bonus number,\n"
        "  total_comp number generated always as (salary + bonus) virtual\n"
        ");\n"
    )
    findings = find_virtual_columns(source)
    assert len(findings) == 1
    assert findings[0].object_name == "EMPLOYEES"
    assert findings[0].severity == "medium"


def test_generated_always_as_without_trailing_virtual_is_flagged():
    # VIRTUAL is optional in Oracle's own grammar -- confirmed via a real
    # ora2pg run that this form converts identically to the full one,
    # losing the same ORA-54016 protection.
    source = "create table employees (a number, b number, c number generated always as (a+b));\n"
    findings = find_virtual_columns(source)
    assert len(findings) == 1


def test_bare_as_expr_with_no_generated_always_is_flagged():
    # The shortest valid Oracle form -- GENERATED ALWAYS is also
    # optional -- confirmed via a real ora2pg run.
    source = (
        "create table employees (\n"
        "  item_id number,\n"
        "  quantity number,\n"
        "  net_value number,\n"
        "  total_value as (item_id * quantity + net_value)\n"
        ");\n"
    )
    findings = find_virtual_columns(source)
    assert len(findings) == 1


def test_ordinary_column_is_not_flagged():
    source = "create table employees (emp_id number, salary number);\n"
    assert find_virtual_columns(source) == []


def test_identity_column_generated_always_is_not_confused_with_a_virtual_column():
    # GAP-028's own territory ('GENERATED ALWAYS AS IDENTITY (...)') --
    # IDENTITY is a bare keyword right after AS, not '(' immediately, so
    # this detector must not fire on it.
    source = "create table employees (emp_id number generated always as identity (start with 1));\n"
    assert find_virtual_columns(source) == []


def test_identity_column_generated_by_default_is_not_confused_with_a_virtual_column():
    source = "create table employees (emp_id number generated by default as identity);\n"
    assert find_virtual_columns(source) == []


def test_expression_with_nested_parens_is_still_matched():
    source = (
        "create table employees (\n"
        "  total_comp number generated always as (salary + nvl(bonus, 0)) virtual\n"
        ");\n"
    )
    findings = find_virtual_columns(source)
    assert len(findings) == 1


def test_multiple_virtual_columns_in_one_table_are_each_flagged():
    source = (
        "create table employees (\n"
        "  gross number generated always as (salary + bonus) virtual,\n"
        "  net number generated always as (salary - tax) virtual\n"
        ");\n"
    )
    findings = find_virtual_columns(source)
    assert len(findings) == 2


def test_bare_ctas_with_no_column_definition_list_is_not_flagged():
    # A bare CTAS has no column-definition list at all for this detector
    # to look at -- same CTAS-scoping reasoning as rowid_type.py.
    source = "create table snap as select salary + bonus as total_comp from employees;\n"
    assert find_virtual_columns(source) == []


def test_reported_line_is_the_as_expr_line():
    source = (
        "create table employees (\n"
        "  emp_id number,\n"
        "  total_comp number generated always as (emp_id) virtual\n"
        ");\n"
    )
    findings = find_virtual_columns(source)
    assert len(findings) == 1
    assert findings[0].line == 3
