from ora2pg_gap_report.autofix import fix_identity_double_parens


def test_strips_the_double_wrap_ora2pg_generates_for_identity_options():
    source = (
        "CREATE TABLE foo (\n"
        "    id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1 INCREMENT BY 1)),\n"
        "    name text\n"
        ");\n"
    )
    fixed, count = fix_identity_double_parens(source)
    assert count == 1
    assert "IDENTITY (START WITH 1 INCREMENT BY 1)" in fixed
    assert "((" not in fixed


def test_leaves_an_already_correct_single_paren_clause_untouched():
    source = "id integer GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_leaves_a_bare_identity_with_no_options_untouched():
    source = "id integer GENERATED ALWAYS AS IDENTITY"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_handles_generated_by_default_as_identity_too():
    source = "id integer GENERATED BY DEFAULT AS IDENTITY ((START WITH 100))"
    fixed, count = fix_identity_double_parens(source)
    assert count == 1
    assert fixed == "id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100)"


def test_fixes_multiple_occurrences_in_one_file():
    source = (
        "CREATE TABLE a (id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1)));\n"
        "CREATE TABLE b (id integer GENERATED ALWAYS AS IDENTITY ((START WITH 2)));\n"
    )
    fixed, count = fix_identity_double_parens(source)
    assert count == 2
    assert "((" not in fixed
    assert "IDENTITY (START WITH 1)" in fixed
    assert "IDENTITY (START WITH 2)" in fixed


def test_does_not_touch_a_double_paren_that_has_extra_content_inside_the_outer_pair():
    # Not the documented bug shape (something else lives inside the outer
    # pair besides just the inner group) -- left alone rather than guessed at.
    source = "id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1) INCREMENT BY 1)"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_returns_the_source_unchanged_when_there_is_no_identity_clause_at_all():
    source = "CREATE TABLE foo (id integer, name text);\n"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_strips_exactly_one_redundant_layer_not_all_of_them():
    # Deliberate, documented behaviour rather than an oversight: ora2pg's
    # actual bug always produces exactly one extra pair, so one pass is a
    # complete fix for every shape it really emits. A hypothetical triple
    # wrap is already invalid PostgreSQL either way, and looping until no
    # parens are left would mean rewriting more aggressively than the
    # evidence supports -- the opposite of this module's whole premise.
    fixed, count = fix_identity_double_parens(
        "id integer GENERATED ALWAYS AS IDENTITY (((START WITH 1)))"
    )
    assert count == 1
    assert fixed == "id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1))"


def test_fixing_is_idempotent_for_the_shape_ora2pg_actually_produces():
    once, n1 = fix_identity_double_parens(
        "id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1 INCREMENT BY 1))"
    )
    twice, n2 = fix_identity_double_parens(once)
    assert n1 == 1
    assert n2 == 0
    assert twice == once


def test_oracle_source_syntax_is_never_rewritten():
    # --write is the only thing in this project that modifies a file, and
    # the single most dangerous mistake a user can make is pointing it at
    # their Oracle source instead of ora2pg's generated output. The bug
    # only ever exists in generated PostgreSQL, so that mistake must be a
    # no-op. Verified separately across 209,793 lines of real open-source
    # Oracle (utPLSQL, alexandria-plsql-utils, db-sample-schemas): zero
    # files would be rewritten. This locks in the same property.
    oracle_source = (
        "CREATE TABLE customers (\n"
        "    customer_id NUMBER GENERATED ALWAYS AS IDENTITY "
        "(START WITH 1 INCREMENT BY 1),\n"
        "    name        VARCHAR2(100)\n"
        ");\n"
        "CREATE OR REPLACE PACKAGE BODY p IS\n"
        "  PROCEDURE go IS BEGIN NULL; END;\n"
        "END p;\n"
    )
    fixed, count = fix_identity_double_parens(oracle_source)
    assert count == 0
    assert fixed == oracle_source
