from ora2pg_gap_report.autofix import fix_identity_double_parens


def test_strips_the_double_wrap_ora2pg_generates_for_identity_options():
    source = (
        "CREATE TABLE foo (\n"
        "    id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1 INCREMENT BY 1)),\n"
        "    name text\n"
        ");\n"
    )
    fixed, count = fix_identity_double_parens(source)
    assert count == 1
    assert "IDENTITY (START WITH 1 INCREMENT BY 1)" in fixed
    assert "((" not in fixed


def test_leaves_an_already_correct_single_paren_clause_untouched():
    source = "id integer GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_leaves_a_bare_identity_with_no_options_untouched():
    source = "id integer GENERATED ALWAYS AS IDENTITY"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_handles_generated_by_default_as_identity_too():
    source = "id integer GENERATED BY DEFAULT AS IDENTITY ((START WITH 100))"
    fixed, count = fix_identity_double_parens(source)
    assert count == 1
    assert fixed == "id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100)"


def test_fixes_multiple_occurrences_in_one_file():
    source = (
        "CREATE TABLE a (id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1)));\n"
        "CREATE TABLE b (id integer GENERATED ALWAYS AS IDENTITY ((START WITH 2)));\n"
    )
    fixed, count = fix_identity_double_parens(source)
    assert count == 2
    assert "((" not in fixed
    assert "IDENTITY (START WITH 1)" in fixed
    assert "IDENTITY (START WITH 2)" in fixed


def test_does_not_touch_a_double_paren_that_has_extra_content_inside_the_outer_pair():
    # Not the documented bug shape (something else lives inside the outer
    # pair besides just the inner group) -- left alone rather than guessed at.
    source = "id integer GENERATED ALWAYS AS IDENTITY ((START WITH 1) INCREMENT BY 1)"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source


def test_returns_the_source_unchanged_when_there_is_no_identity_clause_at_all():
    source = "CREATE TABLE foo (id integer, name text);\n"
    fixed, count = fix_identity_double_parens(source)
    assert count == 0
    assert fixed == source
