"""--migrate: the pipeline's mechanics with a scripted ora2pg everywhere,
and the real ora2pg under the `ora2pg` marker (the CI job that installs
it)."""

import shutil
from pathlib import Path

import pytest

from ora2pg_gap_report import migrate
from ora2pg_gap_report.cli import main
from ora2pg_gap_report.migrate import MARKER_NAME, MigrateError, prepare_out_dir, run_migration, without_packages

SOURCE = """CREATE TABLE orders (id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1), total NUMBER);
CREATE OR REPLACE PACKAGE BODY order_pkg AS
  PROCEDURE close_all IS
  BEGIN
    UPDATE orders SET total = 0;
  END;
END order_pkg;
/
CREATE OR REPLACE PROCEDURE say_it IS
  v VARCHAR2(20) := q'[it's]';
BEGIN
  NULL;
END;
/
"""


class FakeOra2pg:
    """Stands in for ora2pg_wrapper.run_convert: records which input each
    type was run on and returns canned output."""

    def __init__(self, outputs):
        self.outputs = outputs
        self.calls = []

    def __call__(self, input_file, object_type, dialect="oracle", ora2pg_bin="ora2pg", lang="ru"):
        self.calls.append((object_type, input_file.name, input_file.read_text(encoding="utf-8")))
        return self.outputs.get(object_type, "-- Generated by Ora2Pg\nSET client_encoding TO 'UTF8';\n\\set ON_ERROR_STOP ON\n")


@pytest.fixture
def fake(monkeypatch):
    fake = FakeOra2pg(
        {
            "TABLE": "CREATE TABLE orders (id bigint GENERATED ALWAYS AS IDENTITY ((START WITH 1)), total numeric);\n",
            "PACKAGE": "CREATE OR REPLACE PROCEDURE order_pkg.close_all () AS $body$ BEGIN NULL; END; $body$ LANGUAGE plpgsql;\n",
            "PROCEDURE": "CREATE OR REPLACE PROCEDURE say_it () AS $body$ BEGIN NULL; END; $body$ LANGUAGE plpgsql;\n",
        }
    )
    monkeypatch.setattr(migrate, "run_convert", fake)
    return fake


def _source(tmp_path):
    src = tmp_path / "schema.sql"
    src.write_text(SOURCE, encoding="utf-8")
    return src


def test_the_pipeline_writes_every_stage(tmp_path, fake):
    src = _source(tmp_path)
    out = tmp_path / "out"
    result = run_migration([src], out, version="9.9")

    assert (out / MARKER_NAME).exists()
    assert (out / "report.html").read_text(encoding="utf-8").startswith("<!doctype html>")
    assert "GAP-028" in (out / "MIGRATION.md").read_text(encoding="utf-8")
    # prepared copy: the q-quote rewritten, the source untouched
    assert "'it''s'" in (out / "prepared" / "schema.sql").read_text(encoding="utf-8")
    assert "q'[it's]'" in src.read_text(encoding="utf-8")
    assert result.prepared_rewrites == 1
    # only types with content are kept, in load order
    assert [p.name for p in result.converted] == ["03_TABLE_output.sql", "06_PROCEDURE_output.sql", "07_PACKAGE_output.sql"]
    assert "TYPE" in result.empty_types
    # --fix ran on the output: GAP-028's double parens are gone
    assert "IDENTITY (START WITH 1)" in (out / "converted" / "03_TABLE_output.sql").read_text(encoding="utf-8")
    assert result.fixes == 1


def test_only_the_package_run_sees_the_packages(tmp_path, fake):
    run_migration([_source(tmp_path)], tmp_path / "out")
    inputs = {object_type: (name, text) for object_type, name, text in fake.calls}
    assert inputs["PACKAGE"][0] == "_packages.sql" and "PACKAGE BODY" in inputs["PACKAGE"][1]
    assert "say_it" not in inputs["PACKAGE"][1]  # -t PACKAGE would glue it into the body
    for object_type in ("TYPE", "FUNCTION", "PROCEDURE", "TABLE", "TRIGGER"):
        name, text = inputs[object_type]
        assert name == "_standalone.sql" and "PACKAGE" not in text, object_type
        assert "say_it" in text  # the standalone procedure stays


def test_without_packages_cuts_specs_and_bodies_up_to_their_slash():
    source = (
        "CREATE TABLE t (id NUMBER);\n"
        "CREATE OR REPLACE PACKAGE p AS\n  PROCEDURE x;\nEND p;\n/\n"
        "CREATE OR REPLACE EDITIONABLE PACKAGE BODY p AS\n  PROCEDURE x IS BEGIN NULL; END;\nEND p;\n/\n"
        "CREATE OR REPLACE FUNCTION f RETURN NUMBER IS BEGIN RETURN 1; END;\n/\n"
        "-- a comment about CREATE PACKAGE q\n"
    )
    assert without_packages(source) == (
        "CREATE TABLE t (id NUMBER);\n\n\n"
        "CREATE OR REPLACE FUNCTION f RETURN NUMBER IS BEGIN RETURN 1; END;\n/\n"
        "-- a comment about CREATE PACKAGE q\n"
    )


def test_out_dir_that_is_not_ours_is_refused(tmp_path):
    out = tmp_path / "out"
    out.mkdir()
    (out / "notes.txt").write_text("mine", encoding="utf-8")
    with pytest.raises(MigrateError):
        prepare_out_dir(out)
    assert (out / "notes.txt").read_text(encoding="utf-8") == "mine"


def test_a_rerun_replaces_output_and_keeps_checklist_ticks(tmp_path, fake):
    src = _source(tmp_path)
    out = tmp_path / "out"
    run_migration([src], out)
    checklist = out / "MIGRATION.md"
    checklist.write_text(checklist.read_text(encoding="utf-8").replace("- [ ]", "- [x]", 1), encoding="utf-8")
    (out / "converted" / "stale.sql").write_text("old", encoding="utf-8")

    run_migration([src], out)
    assert "- [x]" in checklist.read_text(encoding="utf-8")
    assert not (out / "converted" / "stale.sql").exists()


def test_cli_migrate(tmp_path, fake, capsys):
    src = _source(tmp_path)
    assert main(["--lang", "en", "--migrate", str(tmp_path / "out"), str(src)]) == 0
    text = capsys.readouterr().out
    assert "Migration: Oracle -> PostgreSQL" in text
    assert "add --load-check docker" in text


def test_cli_migrate_refuses_scan_flags_and_foreign_dirs(tmp_path, fake, capsys):
    src = _source(tmp_path)
    assert main(["--lang", "en", "--migrate", str(tmp_path / "o"), "--fix", str(src)]) == 2
    foreign = tmp_path / "foreign"
    foreign.mkdir()
    (foreign / "x").write_text("x", encoding="utf-8")
    assert main(["--lang", "en", "--migrate", str(foreign), str(src)]) == 2
    # Rich wraps a long path (macOS's temp dirs) mid-sentence.
    assert "leaving it alone" in " ".join(capsys.readouterr().err.split())


def test_cli_migrate_explains_a_missing_ora2pg(tmp_path, monkeypatch, capsys):
    from ora2pg_gap_report.ora2pg_wrapper import Ora2PgNotFoundError

    def missing(*args, **kwargs):
        raise Ora2PgNotFoundError("no ora2pg")

    monkeypatch.setattr(migrate, "run_convert", missing)
    assert main(["--lang", "en", "--migrate", str(tmp_path / "out"), str(_source(tmp_path))]) == 2
    assert "--ora2pg-bin docker:IMAGE" in " ".join(capsys.readouterr().err.split())


@pytest.mark.ora2pg
@pytest.mark.skipif(shutil.which("ora2pg") is None, reason="no ora2pg on PATH")
def test_real_ora2pg_converts_each_package_member_once(tmp_path):
    """Without the package cut, -t FUNCTION/PROCEDURE re-extract package
    members unqualified; with it, each member comes out once, from
    -t PACKAGE."""
    sample = Path(__file__).resolve().parents[1] / "docs" / "research" / "samples" / "sql_util_pkg.pkb"
    result = run_migration([sample], tmp_path / "out")
    names = [p.name for p in result.converted]
    assert any("PACKAGE" in n for n in names)
    assert not any("FUNCTION" in n or "PROCEDURE" in n for n in names), names


def test_source_aware_repairs_run_on_the_output(tmp_path, monkeypatch):
    fixtures = Path(__file__).parent / "fixtures" / "source_fixes"
    fake = FakeOra2pg(
        {
            "PACKAGE": (fixtures / "oracle_PACKAGE_output.sql").read_text(encoding="utf-8"),
            "TRIGGER": (fixtures / "oracle_TRIGGER_output.sql").read_text(encoding="utf-8"),
        }
    )
    monkeypatch.setattr(migrate, "run_convert", fake)
    src = tmp_path / "schema.sql"
    shutil.copy(fixtures / "oracle_source.sql", src)
    result = run_migration([src], tmp_path / "out")
    assert result.source_fixes == 5  # one trigger, a default, two reads, a spliced chain
    converted = {p.name.split("_", 1)[1]: p.read_text(encoding="utf-8") for p in result.converted}
    assert "FOR EACH STATEMENT" in converted["TRIGGER_output.sql"]
    assert "current_setting" not in converted["PACKAGE_output.sql"]
