from ora2pg_gap_report.detectors.default_on_null import find_default_on_null_usage
from ora2pg_gap_report.detectors.identity_on_null import find_identity_on_null


def test_an_identity_on_null_column_is_flagged():
    source = "CREATE TABLE orders (\n  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,\n  note VARCHAR2(10)\n);\n"
    findings = find_identity_on_null(source)
    assert [(f.object_name, f.line, f.snippet) for f in findings] == [
        ("ORDERS", 2, "GENERATED BY DEFAULT ON NULL AS IDENTITY")
    ]


def test_the_get_ddl_spelling_is_flagged():
    # Verbatim from a live Oracle 23ai export; ora2pg drops ON NULL from
    # this spelling too.
    source = (
        '  CREATE TABLE "HR"."T_ON_NULL" \n'
        '   (\t"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE '
        "9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  "
        'NOKEEP  NOSCALE  NOT NULL ENABLE, \n\t"NAME" VARCHAR2(10)\n   ) ;\n'
    )
    assert [f.object_name for f in find_identity_on_null(source)] == ["T_ON_NULL"]


def test_identity_without_on_null_is_not_flagged():
    source = (
        "CREATE TABLE t (a NUMBER GENERATED BY DEFAULT AS IDENTITY, "
        "b NUMBER GENERATED ALWAYS AS IDENTITY);\n"
    )
    assert find_identity_on_null(source) == []


def test_a_default_on_null_column_default_is_not_this_gap():
    # That one is GAP-031 (copied verbatim, fails at load).
    assert find_identity_on_null("CREATE TABLE t (s VARCHAR2(9) DEFAULT ON NULL 'x');\n") == []


def test_and_gap_031_no_longer_claims_the_identity_spelling():
    # default_on_null used to flag this with GAP-031's "syntax error at
    # load time", which real ora2pg disproves: it converts the column.
    source = "CREATE TABLE t (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);\n"
    assert find_default_on_null_usage(source) == []
