from ora2pg_gap_report.detectors.identity_column import find_identity_columns_with_options


def test_identity_with_start_and_increment_options_is_flagged():
    source = (
        "create table customers (\n"
        "  customer_id number generated always as identity (start with 1 increment by 1),\n"
        "  name varchar2(100)\n"
        ");\n"
    )
    findings = find_identity_columns_with_options(source)
    assert len(findings) == 1
    assert findings[0].object_name == "CUSTOMERS"
    assert findings[0].severity == "high"


def test_generated_by_default_with_options_is_also_flagged():
    source = "create table customers3 (customer_id number generated by default as identity (start with 100));\n"
    findings = find_identity_columns_with_options(source)
    assert len(findings) == 1


def test_bare_identity_without_options_is_not_flagged():
    # Confirmed empirically: a bare 'GENERATED ALWAYS AS IDENTITY' with no
    # options clause converts correctly -- the bug is specific to the
    # options-clause case.
    source = "create table customers2 (customer_id number generated always as identity, name varchar2(100));\n"
    assert find_identity_columns_with_options(source) == []


def test_ordinary_table_is_not_flagged():
    source = "create table orders (order_id number);\n"
    assert find_identity_columns_with_options(source) == []


def test_unterminated_statement_does_not_bleed_into_an_earlier_table():
    # DBMS_METADATA.GET_DDL's default output (this project's own
    # documented Oracle export mechanism) has no trailing ';' -- scoping
    # "this table's own text" to just "next ';' or end of file" used to
    # let a later table's own identity column bleed all the way back to
    # an earlier, unrelated, unterminated table.
    source = (
        "create table small_lookup (id number)\n"
        "create table customers (customer_id number generated always as identity "
        "(start with 1 increment by 1))\n"
    )
    findings = find_identity_columns_with_options(source)
    assert len(findings) == 1
    assert findings[0].object_name == "CUSTOMERS"
