-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE:

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



-- Oracle package 'bulk_test_pkg' declaration, please edit to match PostgreSQL syntax.
-- Manually remediated per GAP-003 (docs/research/gap-003-bulk-collect-forall.md):
-- the local nested-table TYPE, BULK COLLECT INTO, and FORALL ora2pg left
-- untouched above are not valid PL/pgSQL. Rewritten here using a native
-- PostgreSQL array (bigint[]) and a FOREACH loop -- the fix the gap's own
-- research doc recommends, not a new idiom invented for this example.



CREATE OR REPLACE PROCEDURE bulk_test_pkg_archive_old_orders () AS $body$
DECLARE

    v_ids bigint[];
    v_id bigint;

BEGIN
    SELECT array_agg(order_id)
    INTO v_ids
    FROM orders
    WHERE status = 'CLOSED';

    FOREACH v_id IN ARRAY COALESCE(v_ids, ARRAY[]::bigint[])
    LOOP
      DELETE FROM orders WHERE order_id = v_id;
    END LOOP;

    COMMIT;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE bulk_test_pkg_archive_old_orders () FROM PUBLIC;
-- End of Oracle package 'bulk_test_pkg' declaration
