-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON

CREATE EXTENSION IF NOT EXISTS citext;


CREATE TABLE store (
	store_id integer NOT NULL,
	manager_id integer NOT NULL
) ;
ALTER TABLE store ADD PRIMARY KEY (store_id);
