-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE staff_totals (p_store integer) AS $body$
BEGIN
BEGIN 
   SELECT  store_id, SUM(amount) AS total FROM staff GROUP BY store_id WITH ROLLUP;
END;
GO
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE staff_totals (p_store integer) FROM PUBLIC;

