-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON

CREATE EXTENSION IF NOT EXISTS citext;


CREATE TABLE store (
	store_id integer NOT NULL,
	manager_id integer NOT NULL
) ;
ALTER TABLE store ADD PRIMARY KEY (store_id);


CREATE TABLE staff (
	staff_id integer NOT NULL,
	store_id integer NOT NULL,
	amount integer NOT NULL
) ;
CREATE INDEX staff_idx_fk_store_id ON staff (store_id);
ALTER TABLE staff ADD PRIMARY KEY (staff_id);


CREATE TABLE customer (
	customer_id integer NOT NULL,
	store_id integer NOT NULL
) ;
CREATE INDEX customer_idx_fk_store_id ON customer (store_id);
