-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'gx_ext_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_ext_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_ext_pkg;





CREATE OR REPLACE PROCEDURE gx_ext_pkg.run_it () AS $body$
BEGIN
    RAISE NOTICE 'a';
    pg_sleep(0);
    DBMS_APPLICATION_INFO.SET_MODULE('m', 'a');
    DBMS_APPLICATION_INFO.SET_ACTION('x');
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'GX_EMP');
    DBMS_SCHEDULER.RUN_JOB('J1');
    UTL_FILE.FCLOSE_ALL;
    gx_out_pkg.note('x');
    HTP.P('x');
    OWA_UTIL.MIME_HEADER('text/plain');
    DBMS_UTILITY.EXEC_DDL_STATEMENT('x');
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_ext_pkg.run_it () FROM PUBLIC;
-- End of Oracle package 'gx_ext_pkg' declaration



-- Oracle package 'gx_t_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_t_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_t_pkg;
CREATE DOMAIN gx_t_pkg.t_code AS varchar(10);
CREATE TYPE gx_t_pkg.pair_rt AS (
a integer, b varchar(10)
);

CREATE TYPE gx_t_pkg.num_tt AS (num_tt bigint[]);






CREATE OR REPLACE FUNCTION gx_t_pkg.code_of (p t_code) RETURNS T_CODE AS $body$
DECLARE

    v t_code := p;

BEGIN
    RETURN v || '!';
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_t_pkg.code_of (p t_code) FROM PUBLIC;



CREATE OR REPLACE FUNCTION gx_t_pkg.pair_sum () RETURNS bigint AS $body$
DECLARE

    r pair_rt;

BEGIN
    r.a := 2;
    r.b := '3';
    RETURN r.a + (r.b)::numeric;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_t_pkg.pair_sum () FROM PUBLIC;



CREATE OR REPLACE FUNCTION gx_t_pkg.tab_count () RETURNS bigint AS $body$
DECLARE

    t num_tt;

BEGIN
    t(1) := 5;
    t(2) := 6;
    RETURN t.COUNT;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_t_pkg.tab_count () FROM PUBLIC;
-- End of Oracle package 'gx_t_pkg' declaration

