-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'gx_e_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_e_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_e_pkg;
CREATE DOMAIN gx_e_pkg.t_code AS varchar(10);
CREATE DOMAIN gx_e_pkg.t_emp AS gx_emp%ROWTYPE;
CREATE TYPE gx_e_pkg.emp2_rt AS (
e gx_emp%ROWTYPE, n bigint
);






CREATE OR REPLACE PROCEDURE gx_e_pkg.run_it () AS $body$
DECLARE

    c integer;

BEGIN
    DBMS_OUTPUT.DISABLE;
    -- DBMS_OUTPUT.ENABLE(1000);
    c := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.CLOSE_CURSOR(c);
    pg_sleep(0.1);
    IF c IS NULL THEN pg_sleep(1);END IF;
    DBMS_APPLICATION_INFO.SET_MODULE(module_name => 'm', action_name => NULL);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_e_pkg.run_it () FROM PUBLIC;



CREATE OR REPLACE FUNCTION gx_e_pkg.q (p gx_e_pkg.t_code) RETURNS GX_E_PKG.T_CODE AS $body$
DECLARE

    v gx_e_pkg.t_code := p;

BEGIN
    RETURN v;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e_pkg.q (p gx_e_pkg.t_code) FROM PUBLIC;
-- End of Oracle package 'gx_e_pkg' declaration

