-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'gx_call_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_call_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_call_pkg;





CREATE OR REPLACE PROCEDURE gx_call_pkg.run_it (p text) AS $body$
BEGIN
    CALL gx_out_pkg.note(p);
    CALL gx_out_pkg.note('second ' || p);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_call_pkg.run_it (p text) FROM PUBLIC;
-- End of Oracle package 'gx_call_pkg' declaration



-- Oracle package 'gx_out_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_out_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_out_pkg;





CREATE OR REPLACE PROCEDURE gx_out_pkg.note (p text) AS $body$
BEGIN NULL;END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_out_pkg.note (p text) FROM PUBLIC;
-- End of Oracle package 'gx_out_pkg' declaration



-- Oracle package 'gx_rec_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_rec_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_rec_pkg;
CREATE TYPE gx_rec_pkg.emp_rt AS (
emp_id gx_emp.emp_id%TYPE,
    salary gx_emp.salary%TYPE
  
);

CREATE DOMAIN gx_rec_pkg.t_name AS g_name_def%TYPE;
CREATE DOMAIN gx_rec_pkg.t_sal AS gx_emp.salary%TYPE;





CREATE OR REPLACE FUNCTION gx_rec_pkg.top_salary () RETURNS bigint AS $body$
DECLARE

    r emp_rt;
    s t_sal;

BEGIN
    SELECT emp_id, salary INTO STRICT r FROM gx_emp WHERE emp_id = 2;
    s := r.salary;
    RETURN s;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_rec_pkg.top_salary () FROM PUBLIC;



CREATE OR REPLACE FUNCTION gx_rec_pkg.label (p t_name) RETURNS T_NAME AS $body$
BEGIN
    RETURN '<' || p || '>';
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_rec_pkg.label (p t_name) FROM PUBLIC;
-- End of Oracle package 'gx_rec_pkg' declaration

