-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_l1 (n bigint) RETURNS bigint AS $body$
BEGIN
  RETURN date_trunc('day', n / 3);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l1 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l2 (n bigint) RETURNS bigint AS $body$
BEGIN
  RETURN date_trunc(2, n);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l2 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l3 (n bigint) RETURNS bigint AS $body$
DECLARE

  f double precision(10) := n;

BEGIN
  RETURN f * 2;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l3 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l4 (n bigint) RETURNS bigint AS $body$
DECLARE

  s SIMPLE_INTEGER := 1;
  k NATURAL := 2;
  p POSITIVE := 3;
  g SIGNTYPE := -1;

BEGIN
  RETURN s + k + p + g + n;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l4 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l5 (p text) RETURNS bigint AS $body$
BEGIN
  RETURN INSTR(p, '.', -1) * 10 + INSTR(p, '.', 1, 2);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l5 (p text) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l6 (d1 timestamp(0), d2 timestamp(0)) RETURNS bigint AS $body$
DECLARE

  days bigint;

BEGIN
  days := d1 - d2;
  RETURN days;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l6 (d1 timestamp(0), d2 timestamp(0)) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_l7 (d timestamp(0)) RETURNS varchar AS $body$
DECLARE

  nxt timestamp(0) := d + 1;

BEGIN
  RETURN TO_CHAR(nxt, 'YYYY-MM-DD') || '|' || TO_CHAR(date_trunc('day', d) - 7, 'YYYY-MM-DD');
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_l7 (d timestamp(0)) FROM PUBLIC;

