-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_d1 (n bigint) RETURNS varchar AS $body$
DECLARE

  b integer := n;
  e integer := n;

BEGIN
  RETURN(7 / 2) || '|' || ROUND(b / 2) || '|' || (e / 2);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_d1 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_f1 () RETURNS varchar AS $body$
DECLARE

  a double precision := 0.1;
  b double precision := 0.2;

BEGIN
  IF a + b = 0.3 THEN RETURN 'equal';END IF;
  RETURN 'not equal';
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_f1 () FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_f2 () RETURNS varchar AS $body$
DECLARE

  t double precision;

BEGIN
  SELECT SUM(amount) INTO STRICT t FROM gx_pay;
  RETURN t::text;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_f2 () FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_n1 () RETURNS bigint AS $body$
DECLARE

  v bigint := 2.5;

BEGIN
  RETURN v * 2;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_n1 () FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_n2 (p bigint) RETURNS bigint AS $body$
BEGIN
  RETURN p / 4;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_n2 (p bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_s1 (p text) RETURNS varchar AS $body$
BEGIN
  RETURN SUBSTR(p, 0, 3) || '|' || SUBSTR(p, -3) || '|' || SUBSTR(p, -3, 2) || '|' || SUBSTR(p, 0) || '|' || SUBSTR(p, 2, 2);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_s1 (p text) FROM PUBLIC;

