-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_r1 (a bigint, b bigint) RETURNS varchar AS $body$
BEGIN
  RETURN a/b::text || '|' || -a::text;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_r1 (a bigint, b bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_r2 (n bigint) RETURNS varchar AS $body$
DECLARE

  v real := 0.5;
  d timestamp(0) := timestamp(0) '2026-03-17';

BEGIN
  RETURN v::text || '|' || d::text;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_r2 (n bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_r3 () RETURNS varchar AS $body$
DECLARE

  c char(5) := 'AB';
  v varchar(5) := 'AB';
  l integer;

BEGIN
  SELECT LENGTH(code) INTO STRICT l FROM gx_codes WHERE id = 1;
  RETURN LENGTH(c) || '|' || (c || 'x') || '|' || CASE WHEN c = v THEN 'equal' ELSE 'not equal' END || '|' || l;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_r3 () FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_r4 (d timestamp(0)) RETURNS varchar AS $body$
BEGIN
  RETURN TO_CHAR(ROUND(d, 'MM'), 'YYYY-MM-DD') || '|' || TO_CHAR(ROUND(d), 'YYYY-MM-DD');
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_r4 (d timestamp(0)) FROM PUBLIC;

