-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE orders (
	id serial,
	customer_id integer NOT NULL,
	created_at timestamp without time zone
) ;
CREATE INDEX orders_created_at_idx ON orders (created_at);
CREATE INDEX orders_customer_id ON orders (customer_id);
ALTER TABLE orders ADD PRIMARY KEY (id);


CREATE TABLE invoices (
	id serial,
	customer_id integer NOT NULL
) ;
CREATE INDEX invoices_customer_id ON invoices (customer_id);
ALTER TABLE invoices ADD PRIMARY KEY (id);
