-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON

CREATE EXTENSION IF NOT EXISTS citext;


CREATE TABLE dbo.orders (
	id integer NOT NULL,
	customername citext NOT NULL,
	total numeric(15,4)
) ;
ALTER TABLE dbo.orders ADD CHECK (char_length(customername) <= 100);
ALTER TABLE dbo.orders ADD PRIMARY KEY (id);
