-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION add_one (p integer) RETURNS integer AS $body$
BEGIN
  RETURN p + 1;
END;
$body$
LANGUAGE PLPGSQL
 IMMUTABLE;
-- REVOKE ALL ON FUNCTION add_one (p integer) FROM PUBLIC;

