-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS t_bi ON t CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_t_bi() RETURNS trigger AS $BODY$
BEGIN
  NEW.b := NEW.a;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER t_bi
	BEFORE INSERT ON t FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_t_bi();

