-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE close_order (p_id integer) AS $body$
BEGIN
  UPDATE orders SET status = 'closed' WHERE id = p_id;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE close_order (p_id integer) FROM PUBLIC;

