-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS trg ON language CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg() RETURNS trigger AS $BODY$
BEGIN
  NEW.name := UPPER(NEW.name);
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER trg
	BEFORE UPDATE ON language FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg();

