-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE add_order (p_id integer) AS $body$
BEGIN
BEGIN 
     INSERT  INTO orders(id) VALUES (p_id);
END;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE add_order (p_id integer) FROM PUBLIC;





CREATE OR REPLACE FUNCTION next_id (p_a integer) RETURNS integer AS $body$
BEGIN
BEGIN 
    RETURN p_a + 1;
END;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION next_id (p_a integer) FROM PUBLIC;

