-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW emp_tree AS WITH tree(employee_id, manager_id, lvl) AS (
  SELECT employee_id, manager_id, 1 FROM employees WHERE manager_id IS NULL

UNION ALL

  SELECT e.employee_id, e.manager_id, t.lvl + 1
  FROM employees e JOIN tree t ON e.manager_id = t.employee_id
)
SELECT employee_id, lvl FROM tree;


