-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE page_rows (IN p_offset integer, p_count integer) AS $body$
BEGIN
  SELECT val FROM rows2 ORDER BY id LIMIT 10, 20;
  SELECT val FROM rows2 ORDER BY id LIMIT p_offset, p_count;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE page_rows (IN p_offset integer, p_count integer) FROM PUBLIC;

