-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



-- Oracle package 'hierarchy_demo_pkg' declaration, please edit to match PostgreSQL syntax.
-- Unsupported, please edit to match PostgreSQL syntax
CREATE OR REPLACE TYPE hierarchy_demo_pkg.refcursor AS REFCURSOR;





CREATE OR REPLACE FUNCTION hierarchy_demo_pkg_get_org_chart (p_top_employee_id bigint) RETURNS REFCURSOR AS $body$
DECLARE

    l_cursor refcursor;

BEGIN
    OPEN l_cursor FOR
      WITH RECURSIVE cte AS (
SELECT employee_id,manager_id,1 AS depth,last_name AS org_path
      FROM   employees WHERE employee_id = p_top_employee_id
  UNION ALL
SELECT employee_id,manager_id,(c.level+1) AS depth,c.org_path || '/' || last_name AS org_path
      FROM   employees JOIN cte c ON (c.employee_id = manager_id)

) SELECT * FROM cte;
    RETURN l_cursor;
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION hierarchy_demo_pkg_get_org_chart (p_top_employee_id bigint) FROM PUBLIC;
-- End of Oracle package 'hierarchy_demo_pkg' declaration

-- Total size of package code: 1389 bytes.
-- Total size of package code without comments and header: 322 bytes.
-- Detailed cost per function:
	-- Function hierarchy_demo_pkg.get_org_chart total estimated cost: 6
		-- TEST => 2
		-- CONNECT BY => 1 (cost: 3)
		-- SIZE => 1
-- Total estimated cost for package hierarchy_demo_pkg: 9 units, 1 person-day(s)
