-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION get_org_chart_standalone (p_top_employee_id bigint) RETURNS refcursor AS $body$
DECLARE

  l_cursor REFCURSOR;

BEGIN
  OPEN l_cursor FOR
    WITH RECURSIVE cte AS (
SELECT employee_id,manager_id,1 AS depth,last_name AS org_path
    FROM employees WHERE employee_id = p_top_employee_id
  UNION ALL
SELECT employee_id,manager_id,(c.level+1) AS depth,c.org_path || '/' || last_name AS org_path
    FROM employees JOIN cte c ON (c.employee_id = manager_id)

) SELECT * FROM cte;
  RETURN l_cursor;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION get_org_chart_standalone (p_top_employee_id bigint) FROM PUBLIC;

-- Function get_org_chart_standalone estimated cost: 6.2
	-- CURSOR => 2 (cost: 1)
	-- CONCAT => 2 (cost: 0.1)
	-- TEST => 2
	-- SIZE => 1

-- Total number of functions: 1.
-- Total size of function code: 392 bytes.
-- Total estimated cost: 6.2 units, 1 person-day(s).
