-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'file_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS file_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS file_pkg;





CREATE OR REPLACE FUNCTION file_pkg.sep (p_os text DEFAULT g_os_windows) RETURNS varchar AS $body$
BEGIN
    RETURN CASE WHEN p_os = current_setting('file_pkg.g_os_windows')::varchar(1) THEN 'win' ELSE 'unix' END;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION file_pkg.sep (p_os text DEFAULT g_os_windows) FROM PUBLIC;
-- End of Oracle package 'file_pkg' declaration



-- Oracle package 'fmt_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS fmt_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS fmt_pkg;





CREATE OR REPLACE FUNCTION fmt_pkg.date_fmt () RETURNS varchar AS $body$
BEGIN
    RETURN current_setting('fmt_pkg.c_date')::varchar(30);
  END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION fmt_pkg.date_fmt () FROM PUBLIC;



CREATE OR REPLACE FUNCTION fmt_pkg.stamp_fmt () RETURNS varchar AS $body$
BEGIN
    RETURN current_setting('fmt_pkg.c_stamp')::varchar(30)current_setting('fmt_pkg.c_date')::varchar(30)||;
  END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION fmt_pkg.stamp_fmt () FROM PUBLIC;
-- End of Oracle package 'fmt_pkg' declaration

