-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS gx_t_ai ON gx_orders CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_gx_t_ai() RETURNS trigger AS $BODY$
BEGIN
  UPDATE gx_fired SET n = n + 1;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER gx_t_ai
	AFTER INSERT ON gx_orders FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_gx_t_ai();

