-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE t1 (
	id integer NOT NULL,
	note varchar(200)
) ;
ALTER TABLE t1 ADD UNIQUE ("note(20");
ALTER TABLE t1 ADD PRIMARY KEY (id);


CREATE TABLE t2 (
	id integer NOT NULL
) ;
ALTER TABLE t2 ADD PRIMARY KEY (id);
