-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SEQUENCE gx_cs INCREMENT 1 NO MINVALUE NO MAXVALUE START ;
CREATE SEQUENCE gx_cs1 INCREMENT 1 NO MINVALUE NO MAXVALUE START  CACHE 100;
CREATE SEQUENCE gx_cs3 INCREMENT 1 NO MINVALUE NO MAXVALUE START 5 CACHE 20;
