-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_c1 (a_item text, a_c text DEFAULT '.', a_base integer DEFAULT 0) RETURNS varchar AS $body$
BEGIN
  RETURN trim(both leading a_c from a_item) || '|' || trim(both trailing a_c from a_item) || '|' || a_base;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_c1 (a_item text, a_c text DEFAULT '.', a_base integer DEFAULT 0) FROM PUBLIC;





CREATE OR REPLACE PROCEDURE gx_c2 (p_text text DEFAULT NULL, p_id OUT bigint) AS $body$
BEGIN
  p_id := coalesce(LENGTH(p_text), 0);
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE gx_c2 (p_text text DEFAULT NULL, p_id OUT bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_c3 (p bigint) RETURNS bigint AS $body$
DECLARE

  n#count integer := p;

BEGIN
  RETURN n#count * 2;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_c3 (p bigint) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_c4 (p_xml xml) RETURNS varchar AS $body$
BEGIN
  RETURN p_xml.extract['/a/text()'].getstringval();
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_c4 (p_xml xml) FROM PUBLIC;

