-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_e1 (p text) RETURNS varchar AS $body$
BEGIN
  IF p IS NULL THEN RETURN 'null';END IF;
  RETURN 'value';
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e1 (p text) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_e2 (p text) RETURNS varchar AS $body$
BEGIN
  IF p = '' THEN RETURN 'empty';END IF;
  RETURN 'other';
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e2 (p text) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_e3 (a text, b text) RETURNS varchar AS $body$
BEGIN
  RETURN a || b;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e3 (a text, b text) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_e4 (p text) RETURNS bigint AS $body$
BEGIN
  RETURN LENGTH(p);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e4 (p text) FROM PUBLIC;





CREATE OR REPLACE FUNCTION gx_e5 (p text) RETURNS varchar AS $body$
DECLARE

  v varchar(10) := '';

BEGIN
  IF v IS NULL THEN RETURN 'v is null';END IF;
  RETURN 'v is not null';
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e5 (p text) FROM PUBLIC;

-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE gx_notes (
	id bigint,
	note varchar(20) DEFAULT ''
) ;
-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION gx_e6 (p text) RETURNS varchar AS $body$
BEGIN
  RETURN coalesce(p, '');
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_e6 (p text) FROM PUBLIC;

