import re

from .. import plsql_lex
from ..plsql_lex import TABLE_HEAD, qualified_name_pattern
from ..detector_spec import DetectorSpec, TABLE_COLUMNS, build

_TABLE_RE = re.compile(
    qualified_name_pattern(TABLE_HEAD),
    re.IGNORECASE,
)
_IDENTITY_ON_NULL_RE = re.compile(
    r"\bGENERATED\s+BY\s+DEFAULT\s+ON\s+NULL\s+AS\s+IDENTITY\b",
    re.IGNORECASE,
)

_DOC = """Detect Oracle's GENERATED BY DEFAULT ON NULL AS IDENTITY. In
Oracle an INSERT that supplies NULL for such a column explicitly gets the
next identity value, exactly as if the column had been left out. ora2pg
converts the column to GENERATED BY DEFAULT AS IDENTITY and drops ON NULL
-- the DDL loads, but in PostgreSQL the same INSERT fails with 'null value
in column ... violates not-null constraint'. Code that passes NULL on
purpose (a generic insert routine, an ORM mapping every column) breaks
on its first call. See docs/research/gap-113-identity-on-null.md.

This is also the one DEFAULT ON NULL that GAP-031 does not cover: that
gap is the column default, which ora2pg copies verbatim; this one ora2pg
does rewrite, just without the ON NULL behaviour."""

SPEC = DetectorSpec(
    name="identity_on_null",
    dialect="oracle",
    severity="high",
    pattern=_IDENTITY_ON_NULL_RE,
    strategy=TABLE_COLUMNS,
    snippet="GENERATED BY DEFAULT ON NULL AS IDENTITY",
    statement_pattern=_TABLE_RE,
)

find_identity_on_null = build(SPEC, plsql_lex)
find_identity_on_null.__doc__ = _DOC
