-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE dbo.countorders () AS $body$
DECLARE

;
BEGIN
BEGIN 
     SELECT  COUNT(*) FROM dbo.Orders;
END
GO
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE dbo.countorders () FROM PUBLIC;

