-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS gx_trg ON gx_emp CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_gx_trg() RETURNS trigger AS $BODY$
BEGIN
  NULL;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER gx_trg
	BEFORE INSERT ON gx_emp FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_gx_trg();

