-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'gx_pkg' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS gx_pkg CASCADE;
CREATE SCHEMA IF NOT EXISTS gx_pkg;





CREATE OR REPLACE FUNCTION gx_pkg.f () RETURNS bigint AS $body$
BEGIN RETURN 1;END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION gx_pkg.f () FROM PUBLIC;
-- End of Oracle package 'gx_pkg' declaration

